packages/examples/src/app/my-module/services/user2.controller.ts, packages/sequelize/src/sequelize.service.spec.ts, packages/sequelize/src/sequelize.service.ts
Convert SequelizeService to a generic class so that we can add types on returning values.
=> Convert SequelizeService to a generic class.

packages/core/README.md, packages/core/package.json, packages/core/src/controllers/binders/controller.binder.spec.ts, packages/core/src/controllers/binders/controller.binder.ts, packages/core/src/controllers/binders/rest/rest-controller.binder.ts, packages/core/src/controllers/binders/rest/rest-controller.interface.ts, packages/core/src/controllers/interfaces.ts, packages/examples/src/app/services/user.controller.ts, packages/express/src/get-express-middleware.spec.ts, packages/express/src/get-express-middleware.ts, packages/sequelize/src/sequelize.service.spec.ts, packages/sequelize/src/sequelize.service.ts
- Having contexts defined as `any` prevents from using TypeScript features.
- Adding in a hook custom attributes to the context may conflict with future foal releases if new official attributes appear.
- Having an `id` attribute in the context is only relevant in REST cases.
Define a `Context` interface. It should include:
- useful attributes from the request (headers, session, params, query, etc),
- a `state` attribute where custom attributes can be specified,
- attributes that are not only relevant in REST cases.
=> Redefine Context

docs/packages/sequelize.md
`pg@7` currently not supported (cf [sequelize website](http://docs.sequelizejs.com/manual/installation/getting-started.html))
=> Update pg to pg@6 in sequelize docs

docs/README.md, docs/api/rest-controller.md, docs/basics/controllers.md, docs/basics/modules.md, docs/basics/pre-hooks.md, docs/basics/services.md, docs/packages/sequelize.md
Rename `ts` to `typescript` in doc block code to support [prism](http://prismjs.com/).
=> Prepare docs migrating from gitbook to foalts.org

docs/README.md, docs/advanced/contexts.md, docs/basics/controllers.md, docs/basics/hooks.md, docs/basics/modules.md, docs/basics/services.md, docs/cookbook/authentication.md, docs/packages/sequelize.md
Rename `ts` to `typescript` in doc block code to support [prism](http://prismjs.com/).
=> Prepare docs migrating from gitbook to foalts.org (v0.4.0)

header.txt, packages/authorization/gulpfile.js, packages/authorization/package.json, packages/core/gulpfile.js, packages/core/package.json, packages/examples/gulpfile.js, packages/examples/package.json, packages/express/gulpfile.js, packages/express/package.json, packages/sequelize/gulpfile.js, packages/sequelize/package.json
*Note*: `rm -rf` only works on unix machines. That's why gulp is used here.
=> Clean dist/ folders before building

.travis.yml, README.md, packages/authorization/README.md, packages/authorization/package.json, packages/authorization/tsconfig.json, packages/core/README.md, packages/core/package.json, packages/core/tsconfig.json, packages/examples/README.md, packages/examples/package.json, packages/examples/tsconfig.json, packages/express/README.md, packages/express/package.json, packages/express/tsconfig.json, packages/sequelize/README.md, packages/sequelize/package.json, packages/sequelize/tsconfig.json
- Reduce the size of the distributed code.
- Having async/await in native for better performance.
- [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original) was added in v8.0.0
- On the [Node website](https://nodejs.org/en/) the recommended version to download is v8.9.3
- What are the supported versions of Node on Heroku, ibm cloud, aws, azure, open shift, the linux distributions and the docker images?
- [Node.js ES Support (node.green)](http://node.green/)
- [Node.js Release Working Group](https://github.com/nodejs/Release)
- [Node.js supported versions on AWS](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs)
=> Upgrade to es2017 and node8

packages/common/package.json, packages/common/tsconfig-build.json, packages/common/tsconfig.json, packages/core/package.json, packages/core/tsconfig-build.json, packages/core/tsconfig.json, packages/ejs/package.json, packages/ejs/tsconfig-build.json, packages/ejs/tsconfig.json, packages/examples/package.json, packages/examples/tsconfig-build.json, packages/examples/tsconfig.json, packages/express/package.json, packages/express/tsconfig-build.json, packages/express/tsconfig.json, packages/sequelize/package.json, packages/sequelize/tsconfig-build.json, packages/sequelize/tsconfig.json
Distributed files should not include the tests. However excluding the spec files in the `tsconfig` prevents the IDE from correctly highlighting the code. Creating a separate `tsconfig-build` file fixes that.
=> Add tsconfig-build.json

docs/basics/hooks.md, docs/packages/core.md, packages/core/src/index.ts, packages/core/src/utils/get-post-middleware.spec.ts, packages/core/src/utils/get-post-middleware.ts, packages/core/src/utils/get-pre-middleware.spec.ts, packages/core/src/utils/get-pre-middleware.ts, packages/core/src/utils/index.ts
Testing a hook is not really an easy task. For now, we can only test its middleware and so we have to use a complex code pattern to have a testable hook.
`code`
```typescript
import {
Context,
preHook,
PreMiddleware
} from '@foal/core';
export function makeAddMsgToStateMiddleware(message: string): PreMiddleware {
return function addMsgToStateMiddleware(ctx: Context): void {
ctx.state.message = message;
};
}
export function addMsgToState(message: string) {
return preHook(makeAddMsgToStateMiddleware(message));
}
```
`test`
```typescript
const middleware = makeAddMsgToStateMiddleware('foo');
const ctx = {} as Context;
const ctx.state = {};
middleware(ctx);
expect(ctx.state.message).to.equal('foo');
```
Create `getPreMiddleware` and `getPostMiddleware` which let us retrieve the middleware of …
=> Add getPreMiddleware and getPostMiddleware

docs/README.md, docs/basics/controllers.md, docs/basics/modules.md, docs/packages/ejs.md, docs/packages/sequelize.md, packages/core/src/factories/controller-factory.spec.ts, packages/core/src/factories/controller-factory.ts, packages/core/src/foal.spec.ts, packages/core/src/foal.ts, packages/core/src/interfaces/module.ts, packages/core/src/service-manager.spec.ts, packages/core/src/service-manager.ts, packages/core/src/utils/metadatas.spec.ts, packages/examples/src/app/app.module.ts
Declare services in a module is a bit tedious. It would be great not to have to declare them.
=> Make service declaration optional

docs/packages/common.md, packages/common/src/index.ts, packages/common/src/utils/escape-html.spec.ts, packages/common/src/utils/escape-html.ts, packages/common/src/utils/escape.spec.ts, packages/common/src/utils/escape.ts, packages/common/src/utils/index.ts, packages/core/src/foal.spec.ts
FoalTS needs utils to escape HTML.
=> Add HTML escaping in `@foal/common`

docs/advanced/controller-factories.md, docs/packages/sequelize.md, packages/core/src/factories/controller-factory.spec.ts, packages/core/src/factories/controller-factory.ts, packages/core/src/interfaces/controller-and-routes.ts
Sometimes controller factories may create routes not from a particular service method.
Allow `null` value for `Route.serviceMethodName`.
=> Allow null `Route.serviceMethodName`.

docs/packages/ejs.md
Add a small note on template paths in `@foal/ejs` services.
=> [Doc] Add path note in ejs package.

docs/packages/express.md, packages/express/src/get-callback.ts, packages/express/src/get-express-middleware.spec.ts, packages/express/src/get-express-middleware.ts
It is a pain (and not really useful) to convert some express middlewares such as `csurf` to pre-hooks. It would be nice to keep applying these middlewares to the express app and to forward some of their generated data to `context.state`.
*Note*: For example we can use this feature to forward a `csrf` token and use it in templates (`ctx.state` is used by default to render ejs templates).
=> Add `stateDef` to `getCallback`.

packages/common/src/controller-factories/rest.controller-factory.spec.ts, packages/common/src/controller-factories/rest.controller-factory.ts
In `rest` the route `POST /` returns an entire `HttpResponseCreated` instead of just its content.
=> [rest] Fix POST / bug and add more tests.

docs/packages/authentication.md, packages/authentication/package.json, packages/authentication/src/index.ts, packages/authentication/src/pre-hooks/index.ts, packages/authentication/src/pre-hooks/validate-local-credentials-format.pre-hook.spec.ts, packages/authentication/src/pre-hooks/validate-local-credentials-format.pre-hook.ts
Local authentication needs an easy way to check input data.
Create a `validateLocalCredentialsFormat` pre-hook.
=> Add validateLocalCredentialsFormat

docs/packages/authentication.md, lerna.json, packages/authentication/package.json, packages/authentication/src/email-and-password/index.ts, packages/authentication/src/email-and-password/validate-email-and-password-credentials-format.pre-hook.spec.ts, packages/authentication/src/email-and-password/validate-email-and-password-credentials-format.pre-hook.ts, packages/examples/package.json, packages/examples/src/app/authentication/auth.module.ts
Reasons:
- Name consistency.
- The generator is currently broken on prod: it does not find the searched pre-hook.
=> Fix `validateEmailCredentialsFormat` naming.

packages/cli/src/build.ts
Webpack modes modify/set the value of `process.env.NODE_ENV` when building. This is bad in our case:
- the tests are executed with `process.env.NODE_ENV === 'development'`,
- 3p libraries (ex: express) do not have their `process.env.NODE_ENV` converted which may lead to unexpected behaviors.
Keep using the webpack modes but disable this feature.
=> Do not modify/set the value of process.env.NODE_ENV when building.

packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
A bad csrf token returns a 500 "Internal Server Error".
Make the return app return a 403 'Bad csrf token.'
=> Make the app return 403 'Bad csrf token' when the csrf token is incorrect or missing.

docs/production/deployment-prod.md, packages/cli/src/generate/templates-spec/app/ormconfig.1.json, packages/cli/src/generate/templates/app/ormconfig.json
Creating and running migrations in development is tedious.
Add `synchronize: true` in the generated `ormconfig.json`
=> By default auto create database schema on every application launch 

packages/cli/src/generate/templates-spec/app/ormconfig.1.json, packages/cli/src/generate/templates-spec/app/src/app/entities/user.entity.1.ts, packages/cli/src/generate/templates/app/ormconfig.json, packages/cli/src/generate/templates/app/src/app/entities/user.entity.ts
- Creating migrations fails because `Group` and `Permission` are not found.
- Running the migrations fails because the given path is incorrect.
- Export the entities `Group` and `Permission`.
- Fix the migrations path in `ormconfig.json`
=> Fix commands `npm run migration:generate` and `npm run migration:run`

docs/cookbook/validation.md, packages/core/src/common/hooks/index.ts, packages/core/src/common/hooks/validate-query.hook.spec.ts, packages/core/src/common/hooks/validate-query.hook.ts
Having an easy way to validate the query (`/foo?queryParam1=3&queryParam2=3`) of a request.
Create `ValidateQuery` with the same model as `ValidateBody`.
=> Add ValidateQuery hook

docs/basics/controllers.md, docs/testing/unit-testing.md, packages/cli/src/generate/generators/controller/create-controller.spec.ts, packages/cli/src/generate/generators/controller/create-controller.ts, packages/cli/src/generate/templates-spec/controller/test-foo-bar.controller.empty.ts, packages/cli/src/generate/templates-spec/controller/test-foo-bar.controller.spec.empty.ts, packages/cli/src/generate/templates/controller/controller.empty.ts, packages/cli/src/generate/templates/controller/controller.spec.empty.ts, packages/core/src/auth/authentication/login.controller.spec.ts, packages/core/src/auth/authentication/login.controller.ts, packages/core/src/common/controllers/rest.controller.spec.ts, packages/core/src/core/controllers.spec.ts, packages/core/src/core/controllers.ts, packages/core/src/core/index.ts, packages/core/src/core/routes/make-controller-routes.ts
Bug: controllers inheriting `LoginController` are not instantiated with their dependencies (the `ServiceManager`). This is because the `LoginController` does not have the `Controller` decorator.
This was not caught in the unit tests because the way the "testing child controller" is instantiated is different.
Create a `createController` util to handle the controller instantiation in the unit tests as well as in the FoalTS core.
=> Add `createController` util, fix the LoginController `'get' of undefined` bug and generate with the CLI the tests of empty controllers

docs/production/deployment-prod.md, packages/cli/src/generate/templates-spec/app/package.1.json, packages/cli/src/generate/templates-spec/app/src/index.1.ts, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/src/index.ts, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts, packages/core/src/express/index.ts
- Support custom session stores (https://github.com/FoalTS/foal/issues/107).
- When reloading the server, which happens every time during development, we loose the user authentication. We then have to log in again and again the user.
=>  Support custom session store in create-app

packages/cli/src/generate/templates-spec/app/scripts/create-users.1.ts, packages/cli/src/generate/templates-spec/app/src/app/entities/user.entity.1.ts, packages/cli/src/generate/templates/app/scripts/create-users.ts, packages/cli/src/generate/templates/app/src/app/entities/user.entity.ts
Running the script `create-users.ts` fails since the `User` entity does not have an `email` property nor a `password`.
- Add an email and a password in `user.entity.ts`.
- Comment the lines mentioning any email or password (in both files).
**Note:** Requires also the export fix in https://github.com/FoalTS/foal/pull/173.
=> [@foal/cli] Make `User` entity and `scripts/create-users` consistent.

packages/cli/src/generate/generators/app/create-app.spec.ts, packages/cli/src/generate/generators/app/create-app.ts, packages/cli/src/generate/generators/module/create-module.spec.ts, packages/cli/src/generate/generators/module/create-module.ts, packages/cli/src/generate/templates-spec/app/package.1.json, packages/cli/src/generate/templates-spec/app/src/app/controllers/test.1.ts, packages/cli/src/generate/templates-spec/app/src/app/test.1.ts, packages/cli/src/generate/templates-spec/app/src/test.1.ts, packages/cli/src/generate/templates-spec/app/tsconfig.app.1.json, packages/cli/src/generate/templates-spec/module/controllers/test.1.ts, packages/cli/src/generate/templates-spec/module/test.1.ts, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/src/app/controllers/test.ts, packages/cli/src/generate/templates/app/src/app/test.ts, packages/cli/src/generate/templates/app/src/test.ts, packages/cli/src/generate/templates/app/tsconfig.app.json, packages/cli/src/generate/templates/module/controllers/test.ts, packages/cli/src/generate/templates/module/test.ts
There is no need to build the test files when running `npm run build` or `npm run build:dev`. (https://github.com/FoalTS/foal/issues/180).
=> Do not build test when running npm run build.

docs/cookbook/template-engine.md, docs/security/authentication.md, docs/security/csrf-protection.md, packages/cli/src/generate/generators/app/create-app.spec.ts, packages/cli/src/generate/generators/app/create-app.ts, packages/cli/src/generate/generators/module/create-module.spec.ts, packages/cli/src/generate/generators/module/create-module.ts, packages/cli/src/generate/templates-spec/app/src/app/controllers/templates/index.1.ts, packages/cli/src/generate/templates-spec/app/src/app/controllers/view.controller.1.ts, packages/cli/src/generate/templates/app/src/app/controllers/templates/index.ts, packages/cli/src/generate/templates/app/src/app/controllers/view.controller.ts, packages/core/src/common/utils/render.util.spec.ts, packages/core/src/common/utils/render.util.ts, packages/ejs/src/index.spec.ts, packages/ejs/src/index.ts, packages/examples/src/app/controllers/auth.controller.ts, packages/examples/src/app/controllers/templates/index.ts, packages/examples/src/app/controllers/view.controller.ts
Be able to specify the template path in `render` to not write `readFileSync(join(__dirname, './templates/index.html'), 'utf8')` (https://github.com/FoalTS/foal/issues/179).
Use this interface:
```typescript
render(templatePath: string, locals: object, dirname: string): HttpResponseOK;
```
=> Make render use template paths.

docs/cookbook/validation.md, docs/guide/4-rest-api-endpoint.md, packages/cli/src/generate/specs/service/test-foo-bar.service.entity-resource-collection.ts, packages/cli/src/generate/templates/service/service.entity-resource-collection.ts, packages/core/src/common/utils/index.ts, packages/core/src/common/utils/validate.util.spec.ts, packages/core/src/common/utils/validate.util.ts
- Schema validation should be done in the blink of an eye.
- Currently there is no "get started" to properly use an `EntityResourceCollection` with data validation.
=> Add validate util and add it by default when generating an `EntityResourceCollection`

.gitignore, .travis.yml, docs/the-authentication-system/permissions-and-authorization.md, e2e_test.sh, packages/cli/package.json, packages/cli/src/generate/generators/app/create-app.spec.ts, packages/cli/src/generate/generators/app/create-app.ts, packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/src/app/controllers/view.controller.spec.ts, packages/cli/src/generate/specs/app/src/app/controllers/view.controller.ts, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/src/app/controllers/view.controller.spec.ts, packages/cli/src/generate/templates/app/src/app/controllers/view.controller.ts
FoalTS lacks of e2e tests. We need to make sure that the "get started" (creating and running a single app), most of the generators, the linting and the default shell scripts always work.
Add an `e2e_test.sh` bash script to create an app and run the basic commands.
=> [Internal] Add e2e tests in Travis

docs/development-environment/create-and-run-scripts.md, e2e_test.sh, packages/cli/src/generate/generators/index.ts, packages/cli/src/generate/generators/script/create-script.spec.ts, packages/cli/src/generate/generators/script/create-script.ts, packages/cli/src/generate/generators/script/index.ts, packages/cli/src/generate/specs/script/test-foo-bar.ts, packages/cli/src/generate/templates/script/script.ts, packages/cli/src/index.ts
- Creating a script file by hand is a bit tedious.
- It should be easy to users to get started with scripts.
=> Add the script generator

README.md, docs/development-environment/code-generation.md, packages/cli/src/generate/generators/controller/create-controller.spec.ts, packages/cli/src/generate/generators/controller/create-controller.ts, packages/cli/src/generate/generators/controller/register-controller.ts, packages/cli/src/generate/mocks/controller/app.module.controller-import.ts, packages/cli/src/generate/mocks/controller/app.module.core-import.ts, packages/cli/src/generate/mocks/controller/app.module.empty-property.ts, packages/cli/src/generate/mocks/controller/app.module.empty-spaced-property.ts, packages/cli/src/generate/mocks/controller/app.module.no-controller-import.ts, packages/cli/src/generate/mocks/controller/app.module.no-empty-property.ts, packages/cli/src/generate/mocks/controller/app.module.rest.ts, packages/cli/src/generate/specs/controller/app.module.controller-import.ts, packages/cli/src/generate/specs/controller/app.module.core-import.ts, packages/cli/src/generate/specs/controller/app.module.empty-property.ts, packages/cli/src/generate/specs/controller/app.module.empty-spaced-property.ts, packages/cli/src/generate/specs/controller/app.module.no-controller-import.ts, packages/cli/src/generate/specs/controller/app.module.no-empty-property.ts, packages/cli/src/generate/specs/controller/app.module.rest.ts, packages/cli/src/generate/utils/generator.ts, packages/cli/src/index.ts, tslint.json
It is tedious to always have to register the controllers in `app.module.ts` upon creation. Especially it does not facilitate the "on-boarding" process.
Add the option `--register` to `foal g controller foo-bar` that seeks for the `app.module.ts` and automatically registers the controller within the module class.
=> Automatically register controllers upon creation.

docs/development-environment/create-and-run-scripts.md, docs/the-authentication-system/permissions-and-authorization.md, e2e_test.sh, packages/cli/package.json, packages/cli/src/generate/specs/app/src/scripts/create-group.ts, packages/cli/src/generate/specs/app/src/scripts/create-perm.ts, packages/cli/src/generate/specs/app/src/scripts/create-user.ts, packages/cli/src/generate/specs/script/test-foo-bar.ts, packages/cli/src/generate/templates/app/src/scripts/create-group.ts, packages/cli/src/generate/templates/app/src/scripts/create-perm.ts, packages/cli/src/generate/templates/app/src/scripts/create-user.ts, packages/cli/src/generate/templates/script/script.ts, packages/cli/src/index.ts, packages/cli/src/run-script.spec.ts, packages/cli/src/run-script.ts, packages/core/src/common/utils/get-command-line-arguments.util.spec.ts, packages/core/src/common/utils/get-command-line-arguments.util.ts
- Currently we define a `main` function that is called directly in each script. This prevents the user from easily writing unit tests.
- (Writing `node lib/scripts/my-scripts.js` is a bit tedious).
Create a command `foal run-script my-script` that runs the scripts by calling their `main` function.
=> Add the `foal run-script` feature.

packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/templates/app/package.json, packages/examples/package.json
Fix https://github.com/FoalTS/foal/issues/204.
=> Correcting typeorm scripts - Issue #204

.travis.yml, README.md, packages/core/package.json
Code coverage should be displayed in the `README.md` to show that the framework has tests. See https://github.com/FoalTS/foal/issues/136.
Use codecov.io
Only the code coverage of the package `@foal/core` is computed. The packages `@foal/cli` and `@foal/ejs` should also be included in the computation.
=> Display code coverage with codecov

packages/cli/src/generate/generators/app/create-app.spec.ts, packages/cli/src/generate/generators/app/create-app.ts, packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/src/test.ts, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/src/test.ts
Test do not run with `NODE_ENV=test` causing the configuration not to use the `xxx.test.json` files (issue https://github.com/FoalTS/foal/issues/187).
The solution should work both on Windows and Unix systems.
=> Make the tests run with NODE_ENV=test (on Unix/Windows)

docs/guide/3-flight-model.md, docs/the-authentication-system/authentication.md, packages/cli/src/generate/specs/app/src/app/entities/user.entity.ts, packages/cli/src/generate/specs/app/tsconfig.json, packages/cli/src/generate/specs/entity/test-foo-bar.entity.ts, packages/cli/src/generate/templates/app/src/app/entities/user.entity.ts, packages/cli/src/generate/templates/app/tsconfig.json, packages/cli/src/generate/templates/entity/entity.ts, packages/cli/tsconfig.json, packages/core/e2e/auth.spec.ts, packages/core/e2e/rest.spec.ts, packages/core/src/auth/authentication/authenticate.hook.spec.ts, packages/core/src/auth/authentication/strategies/email/email-authenticator.service.spec.ts, packages/core/src/auth/entities/abstract-user.entity.ts, packages/core/src/auth/entities/group.entity.ts, packages/core/src/auth/entities/permission.entity.ts, packages/core/src/common/services/entity-resource-collection.service.spec.ts, packages/core/tsconfig.json, packages/ejs/tsconfig.json, packages/password/tsconfig.json
Having some `@ts-ignore` everywhere in the doc is confusing to people getting started with `TypeScript` (and the strict mode)
Set `strictPropertyInitialization` by default to `false` in `tsconfig.json`.
=> Set `strictPropertyInitialization` to `false` in `tsconfig.json` and remove the `ts-ignore`.

docs/cookbook/validation.md, packages/core/src/common/hooks/index.ts, packages/core/src/common/hooks/validate-body.hook.spec.ts, packages/core/src/common/hooks/validate-body.hook.ts, packages/core/src/common/hooks/validate-headers.hook.spec.ts, packages/core/src/common/hooks/validate-headers.hook.ts, packages/core/src/common/hooks/validate-params.hook.spec.ts, packages/core/src/common/hooks/validate-params.hook.ts, packages/core/src/common/hooks/validate-query.hook.spec.ts, packages/core/src/common/hooks/validate-query.hook.ts, packages/core/src/common/utils/get-ajv-instance.spec.ts, packages/core/src/common/utils/get-ajv-instance.ts, packages/core/src/common/utils/validate.util.ts
Add an internal util `getAjvInstance` than returns a single instance of Ajv which has this configuration:
```typescript
{
coerceTypes: true,  // change data type of data to match type keyword
removeAdditional: true, // remove additional properties
useDefaults: true, // replace missing properties and items with the values from corresponding default keyword
}
```
=> Make ajv global instance coerce types, remove additional properties if required and use default values and add ValidateHeaders/ValidateParams

docs/development-environment/vscode.md, packages/cli/src/generate/generators/index.ts, packages/cli/src/generate/generators/vscode-config/create-vscode-config.spec.ts, packages/cli/src/generate/generators/vscode-config/create-vscode-config.ts, packages/cli/src/generate/generators/vscode-config/index.ts, packages/cli/src/generate/specs/vscode-config/launch.json, packages/cli/src/generate/specs/vscode-config/tasks.json, packages/cli/src/generate/templates/vscode-config/launch.json, packages/cli/src/generate/templates/vscode-config/tasks.json, packages/cli/src/index.ts
Starting to debug a FoalTS application with VSCode is not straightforward.
Having a command which generates the suitable vscode config files to start the app with the IDE debugger.
=> Generate vscode config files for fast debugging

docs/cookbook/basic-logging.md, packages/core/src/common/hooks/log.hook.spec.ts, packages/core/src/common/hooks/log.hook.ts
The `Log` function is not sufficient. Sometimes we need to print information about the HTTP request with the message. 
Add four options to the `Log` hook to print the body, query, params or headers of the HTTP request.
=> Let the Log hook print information about the HTTP request.

docs/authentication-and-access-control/usage-in-web-requests.md, packages/core/src/auth/authentication/login.controller.ts, packages/core/src/auth/index.ts, packages/core/src/auth/utils/index.ts, packages/core/src/auth/utils/log-in.util.spec.ts, packages/core/src/auth/utils/log-in.util.ts, packages/core/src/auth/utils/log-out.util.spec.ts, packages/core/src/auth/utils/log-out.util.ts
Log users in or out without the `LoginController` is hard.
Add two utilities `logIn` and `logIn` to attach/detach a user to/from a session.
=> Add the logIn and logOut utilities.

docs/authentication-and-access-control/usage-in-web-requests.md, docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md, docs/tutorials/multi-user-todo-list/6-todos-and-ownership.md, docs/tutorials/multi-user-todo-list/7-the-signup-page.md, docs/tutorials/simple-todo-list/5-the-rest-api.md, docs/tutorials/simple-todo-list/6-validation-and-sanitization.md, docs/tutorials/simple-todo-list/7-unit-testing.md, packages/cli/src/generate/generators/controller/create-controller.ts, packages/cli/src/generate/specs/controller/app.controller.empty-property.ts, packages/cli/src/generate/specs/controller/app.controller.empty-spaced-property.ts, packages/cli/src/generate/specs/controller/app.controller.no-empty-property.ts
When using the option `--register` with the command `foal generate controller`, the controllers are registered with the default path `/`.
This is annoying for two reasons.
- Usually when creating an `ApiController`, we'd like to bind the controller to the route `/api`.
- Having the same path `/` for each controller may lead to tricky bugs when two controllers have a method with another same path (they handle the same route).
Register the controllers with their kebab name by default.
=> [@foal/cli] Register the controllers with their kebab name.

docs/architecture/controllers.md, docs/architecture/hooks.md, docs/cookbook/template-engine.md, docs/cookbook/validation.md, docs/tutorials/simple-todo-list/7-unit-testing.md, packages/core/src/auth/authentication/login.controller.spec.ts, packages/core/src/common/controllers/rest.controller.spec.ts, packages/core/src/common/hooks/validate-body.hook.spec.ts, packages/core/src/common/hooks/validate-headers.hook.spec.ts, packages/core/src/common/hooks/validate-params.hook.spec.ts, packages/core/src/common/hooks/validate-query.hook.spec.ts, packages/core/src/common/utils/render.util.spec.ts, packages/core/src/core/http/http-responses.spec.ts, packages/core/src/core/http/http-responses.ts, packages/core/src/express/create-middleware.spec.ts, packages/core/src/express/create-middleware.ts
The developer should be able to send cookies in their http responses.
The property `headers` of `HttpResponse` is now private. You need to use the `setHeader`, `getHeader` and `getHeaders` methods instead.
=> Support cookies and headers in the `HttpResponse` objects

docs/architecture/hooks.md, packages/core/src/auth/authentication/authenticate.hook.spec.ts, packages/core/src/core/hooks.spec.ts, packages/core/src/core/hooks.ts, packages/core/src/express/create-middleware.spec.ts, packages/core/src/express/create-middleware.ts
Sometimes we want to execute functions after the execution of the controller method. See https://github.com/FoalTS/foal/issues/163.
Let the hooks return a `HookPostFunction` that will be executed after the method execution.
```typescript
type HookPostFunction = (ctx: Context, services: ServiceManager, response: HttpResponse) => void | Promise<void>;
```
=> [@foal/core] Add "post function" feature in hooks

docs/architecture/controllers.md, packages/core/src/core/http/http-methods.spec.ts, packages/core/src/core/http/http-methods.ts, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
The HTTP methods `OPTIONS` and `HEAD` are currently not supported. This causes trouble especially when it deals to create a public API (see https://github.com/FoalTS/foal/issues/259).
=> Add OPTIONS and HEAD http methods.

docs/authentication-and-access-control/usage-in-web-requests.md, docs/tutorials/multi-user-todo-list/6-todos-and-ownership.md, docs/tutorials/simple-todo-list/5-the-rest-api.md, packages/cli/src/generate/specs/app/src/app/app.controller.ts, packages/cli/src/generate/templates/app/src/app/app.controller.ts, packages/core/e2e/auth.spec.ts, packages/core/e2e/rest.spec.ts, packages/core/src/auth/authentication/authenticate.hook.spec.ts, packages/core/src/auth/authentication/authenticate.hook.ts, packages/examples/src/app/app.controller.ts
The name `Authenticate` is not very clear as it does not give information on how the user is authenticated. Future versions of FoalTS will include other ways to authenticate a user (JWT, see https://github.com/FoalTS/foal/issues/254). It would be great to clearly differentiate these methods.
Rename the hook `Authenticate` to `AuthenticateWithSessionAndCookie`.
=> Rename Authenticate to AuthenticateWithSessionAndCookie

packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
All the features of FoalTS have not been implemented yet. By then, it would be useful to be able to use app-level express middlewares (like `cors`). It is a bit hacky but it will let us fully use the framework.
Related issues: https://github.com/FoalTS/foal/issues/259, https://github.com/FoalTS/foal/issues/259.
Add an optional parameter `expressInstance` to `createApp`.
=> Let createApp accept a custom express instance as base

packages/cli/src/generate/specs/controller/test-foo-bar.controller.spec.empty.ts, packages/cli/src/generate/templates/controller/controller.spec.empty.ts
Fix https://github.com/FoalTS/foal/issues/239.
Create a `Context` object in the controller spec.
=> [@foal/cli] Fix controller spec typo (add a context object)

README.md, docs/tutorials/simple-todo-list/1-installation.md, e2e_test.sh, packages/cli/README.md, packages/cli/src/generate/generators/app/create-app.ts, packages/cli/src/index.ts, packages/core/README.md, packages/ejs/README.md, packages/password/README.md
When creating a new project, the dependencies are not automatically installed. The user has "too many" commands to enter to create and start the app.
Auto install the dependencies  with npm  upon creation (or with yarn if it is installed).
=> [@foal/cli] Auto install dependencies upon project creation

packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
See #283 
Add a custom express middleware in `createApp` when `csrf` is false.
=> [@foal/core] Add empty csrfToken function when csrf=false

docs/architecture/services.md, docs/development-environment/code-generation.md, docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md, docs/tutorials/multi-user-todo-list/7-the-signup-page.md, docs/tutorials/simple-todo-list/5-the-rest-api.md, e2e_test.sh, packages/cli/package.json, packages/cli/src/index.ts
See #288.
Remove the prompts of the commands `foal g controller` and `foal g service` to prevent the user from generating deprecated files.
=> [@foal/cli] Remove the prompts from "foal g controller|service"

docs/utilities/logging-and-debugging.md, packages/cli/src/generate/specs/app/config/settings.development.json, packages/cli/src/generate/specs/app/config/settings.json, packages/cli/src/generate/templates/app/config/settings.development.json, packages/cli/src/generate/templates/app/config/settings.json, packages/core/src/express/create-app.ts
FoalTS displays logs upon requests. It would be nice to be able to customize them.
Add an option in the `Config` to the specify the string format (see https://www.npmjs.com/package/morgan)
=> Be able to customize the logger outputs

packages/cli/src/index.ts
Closes #308 
- If the user fires in `foal` nothing shows up. 
- User can fire in any command without any sort of warnings
- Shows up help if no arguments are supplied
- Warns the user on firing in random commands with `foal`
=> Validates random commands and shows up help if none supplied

docs/authentication-and-access-control/groups-and-permissions.md, docs/authentication-and-access-control/user-class.md, docs/development-environment/create-and-run-scripts.md, docs/tutorials/mongodb-todo-list/2-with-typeorm.md, docs/tutorials/multi-user-todo-list/3-the-shell-scripts.md, docs/tutorials/simple-todo-list/4-the-shell-script-create-todo.md, e2e_test.sh, packages/cli/src/index.ts
The command `foal run-script <name>` is too long.
Add the alias `foal run <name>`.
=> [@foal/cli] Add `foal run` as alias of `foal run-script`

packages/cli/src/generate/generators/app/create-app.ts, packages/cli/src/generate/utils/generator.ts, packages/cli/src/generate/utils/index.ts, packages/cli/src/generate/utils/init-git-repo.ts, packages/cli/src/index.ts
- Almost every project uses Git. It is tedious to have to run `git init`, `git add .` and `git commit` after the project creation.
- When creating a new project the banner goes away because the paths of the generated files are printed (see #314).
- Auto init a git repo on every new project. If the project is already in a git repo then skip.
- Improve the console UI.
=> [@foal/cli] `foal createapp`: prettify the outputs and auto initialize git repo.

e2e_test.sh, packages/jwt/src/jwt-optional.hook.ts, packages/jwt/src/jwt-required.hook.ts
The compilation of the package `@foal/jwt` includes an error. The returned type of `JWTRequired` and `JWTOptional` is `import("../../../../../../../../Users/loicpoullain/projects/FoalTS/foal/packages/jwt/node_modules/@foal/core/lib/core/hooks").HookDecorator;` which may make fail the `npm run develop` command.
Do not let typescript infer the return type of the hooks. Add it manually
=> Fix type error in JWTOptional and JWTRequired

packages/cli/src/generate/generators/app/create-app.ts
> Closes #313
User can provide any sort of special characters for the  `projectName` with `foal createapp` which doesn't make any sense.
For instance, `foal createapp !@#` works as per now.
Validate the name provided as an argument and show warnings appropriately.
=> Validate project name as per npm conventions

docs/tutorials/simple-todo-list/5-the-rest-api.md, docs/tutorials/simple-todo-list/6-validation-and-sanitization.md
The `get-started` tutorial has some typos. See [here](https://www.reddit.com/r/typescript/comments/akn2xg/foalts_a_web_framework_for_building_serverside/ef8x6aq) the comment on reddit.
Fix these things:
=> Fix typos in the `get-started` tutorial

docs/authentication-and-access-control/jwt.md, packages/jwt/e2e/jwt.spec.ts, packages/jwt/src/jwt.hook.spec.ts, packages/jwt/src/jwt.hook.ts
=> Allow `JWTRequired` and `JWTOptional` retrieve the tokens from a cookie

e2e_test.sh, packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.current-dir.ts, packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.ts, packages/cli/src/generate/templates/rest-api/controller.current-dir.ts, packages/cli/src/generate/templates/rest-api/controller.ts
=> [@foal/cli] Validate params in REST APIs

docs/validation-and-sanitization.md, packages/core/src/common/utils/get-ajv-instance.spec.ts, packages/core/src/common/utils/get-ajv-instance.ts
Resolves #343 .
- Make `getAjvInstance` use `Config`.
=> Allow customized configuration for getAjvInstance

packages/cli/src/generate/specs/app/config/default.json, packages/cli/src/generate/specs/app/config/default.yml, packages/cli/src/generate/templates/app/config/default.json, packages/cli/src/generate/templates/app/config/default.yml, packages/typeorm/e2e/auth-redirect.spec.ts
Having a session cookie path not set makes the authentication to fail in some situations. See #357.
=> [@foal/cli] Set the default cookie path to `/` in `config/`.

packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/cli/src/generate/templates/app/package.mongodb.yaml.json, packages/cli/src/generate/templates/app/package.yaml.json
The package `typeorm` now requires TypeScript 3.3 or greater since the version `0.2.15`, causing the build to fail on every new project with Foal (see #377).
Every new project will start with the version 3.3 of the TypeScript Compiler or greater (instead of v2.9.2).
This won't introduce any breaking changes since the framework code is compatible with both versions 2 or 3 of TypeScript (see [here](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes)).
=> [@foal/cli] Upgrade TSC to version 3 or greater

packages/cli/src/generate/specs/app/src/e2e.ts, packages/cli/src/generate/specs/app/src/test.ts, packages/cli/src/generate/templates/app/src/e2e.ts, packages/cli/src/generate/templates/app/src/test.ts
See #385.
The tracebacks of the errors thrown during unit or e2e tests do not use the source maps. Thus the errors refer to the JS files and not the TS ones.
=> [@foal/cli] Use source maps during testing

docs/SUMMARY.md, docs/utilities/static-files.md, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
See #382 
Add the settings.staticPathPrefix option.
=> Let developers specify a virtual path prefix for static files

docs/deployment-and-environments/configuration.md, packages/core/src/core/config-mock.spec.ts, packages/core/src/core/config-mock.ts, packages/core/src/core/index.ts, packages/jwt/src/jwt.hook.spec.ts, packages/jwt/src/jwt.hook.ts
=> Add a class `ConfigMock` to mock the `Config` when it used as a service

docs/validation-and-sanitization.md, packages/core/src/common/hooks/index.ts, packages/core/src/common/hooks/validate-cookies.hook.ts, packages/core/src/common/hooks/validate-cookies.spec.ts
See #375 
Just add a ValidateCookies hook like ValidateBody.
=> Validate cookie

packages/cli/src/generate/generators/angular/connect-angular.spec.ts, packages/cli/src/generate/generators/app/create-app.spec.ts, packages/cli/src/generate/generators/controller/create-controller.spec.ts, packages/cli/src/generate/generators/entity/create-entity.spec.ts, packages/cli/src/generate/generators/hook/create-hook.spec.ts, packages/cli/src/generate/generators/model/create-model.spec.ts, packages/cli/src/generate/generators/react/connect-react.spec.ts, packages/cli/src/generate/generators/rest-api/create-rest-api.spec.ts, packages/cli/src/generate/generators/script/create-script.spec.ts, packages/cli/src/generate/generators/service/create-service.spec.ts, packages/cli/src/generate/generators/sub-app/create-sub-app.spec.ts, packages/cli/src/generate/generators/vscode-config/create-vscode-config.spec.ts, packages/cli/src/generate/generators/vue/connect-vue.spec.ts, packages/cli/src/generate/utils/index.ts, packages/cli/src/generate/utils/rm-dir-and-files-if-exist.ts, packages/cli/src/generate/utils/test-environment.ts, packages/cli/src/run-script/run-script.spec.ts
In the `afterEach` step during testing, it is tedious to specify all the files to delete.
Add and use a utility called `rmDirAndFilesIfExist`.
=> [Internal] [@foal/cli] Add and use rmDirAndFilesIfExist in the tests

packages/core/src/common/hooks/log.hook.spec.ts, packages/core/src/common/hooks/log.hook.ts
See #409 
Make the option `header` be insensitive to the case.
=> Fix case-sensitive headers in Log hook

docs/security/http-headers-protection.md, packages/core/package-lock.json, packages/core/package.json, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
The `@foal/core` package depends indirectly on 99 packages. Depending on too many packages increases the `node_modules` size and reduces the framework security.
Remove [helmet](https://www.npmjs.com/package/helmet) (19 indirect dependencies) by manually setting the response headers.
=> Reduce the number of dependencies of the core package (by removing helmet).

docs/api-section/public-api-and-cors-requests.md
Resolves #416.
```
Access to XMLHttpRequest at 'some_origin' from origin 'another_origin' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
```
Add documentation on how to solve this issue.
=> [Docs] CORS - Add docs on the Authorization header

docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
=> Fix typo in docu

packages/core/src/core/config.spec.ts, packages/core/src/core/config.ts
Resolves #437.
- Replace `parseInt` with `Number` and add other checks.
=> Fix invalid data parsing in Config

docs/architecture/hooks.md, packages/core/src/core/hooks.spec.ts, packages/core/src/core/hooks.ts
=> Add @MergeHooks to be able to group several hooks into one.

packages/jwks-rsa/package-lock.json
Snyk reported that the current `package-lock.json` in the package `@foal/jwks-rsa` has a prototype pollution. This PR fixes the version of `lodash` that is responsible for this.
=> [jwks-rsa] Update insecure package-lock.json

packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts, packages/core/src/express/handle-errors.ts
Fixes #457.
- Make the app return a pretty 400 object message if the JSON received is invalid.
- Make the app return the client errors thrown in the internals middlewares.
=> [Bug] Fix 500 errors on invalid JSON

packages/cli/src/generate/generators/controller/create-controller.spec.ts, packages/cli/src/generate/generators/controller/create-controller.ts, packages/cli/src/generate/generators/entity/create-entity.spec.ts, packages/cli/src/generate/generators/entity/create-entity.ts, packages/cli/src/generate/generators/hook/create-hook.spec.ts, packages/cli/src/generate/generators/hook/create-hook.ts, packages/cli/src/generate/generators/model/create-model.spec.ts, packages/cli/src/generate/generators/model/create-model.ts, packages/cli/src/generate/generators/service/create-service.spec.ts, packages/cli/src/generate/generators/service/create-service.ts
Currently `foal generate controller` fails if there is no `index.ts` file in `src/app/controllers`, `controllers` or in the current directory. This a bit annoying when organizing the directory structure by functionality.
=> [Bug] Make `foal generate` not fail if index.ts does not exist

docs/api-section/public-api-and-cors-requests.md, docs/cookbook/limit-repeated-requests.md
Resolves #485
Added example code to the docs to show how to set headers to a response from `express-rate-limit`.
=> [Docs] Adds CORS example for rate limiting

packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/cli/src/generate/templates/app/package.mongodb.yaml.json, packages/cli/src/generate/templates/app/package.yaml.json, packages/swagger/src/swagger-controller.ts
Resolves #528.
Theoretically, minor releases of TypeScript (3.4, 3.5, 3.6, etc) should not break code compatibility. In practice, when TS releases a new version, they often introduce a small breaking change / bug that libraries need to fix to make them work with the new version. We had this issue twice with TypeORM in Foal history.
This is annoying because when a new TS version is released, the command `foal createapp` installs this last version and `foal develop` (or other build commands) might not work (that make us loose people that might give the framework a try).
Make `foal createapp` generate every new project with TypeScript version 3.5 (and its patches).
=> [CLI] Set default TS version to 3.5 in new projects (foal createapp)

docs/SUMMARY.md, docs/cookbook/initialization.md, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts, packages/core/src/express/index.ts
Resolves #517.
This function is the same as `createApp` except that it calls `AppController.init` if it exists and it returns a promise (to allow `AppController.init` to be asynchronous).
=> Support AppController.init to initialize the application

docs/cookbook/expressjs.md, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
In some situations, we may need to specify both an `expressInstance` and `postMiddlewares` to `createApp` (for example if we're migrating an application from Express to Foal). This is currently not possible to do it properly.
See this discussion: #370
=> Support ExpressOptions.expressInstance in createApp

packages/graphql/src/graphql.controller.spec.ts, packages/graphql/src/graphql.controller.ts
Ajv schema validation fails if graphql query variables is `null`. 
For example `{"query":"{ users { email } }","variables":null}` returns 
```js
[
{
"keyword": "type",
"dataPath": ".variables",
"schemaPath": "#/properties/variables/type",
"params": {
"type": "object"
},
"message": "should be object"
}
]
```
Update Ajv schema to accept `null` for variables.
=> Accept null as graphql query variables

packages/cli/src/generate/generators/app/create-app.spec.ts, packages/cli/src/generate/generators/app/create-app.ts, packages/cli/src/generate/utils/init-git-repo.ts, packages/cli/src/index.ts
* No way to stop createapp from automagically choosing between npm and yarn, and the installing process is quite slow (and may be skipped).
* No way to stop createapp from creating a git repository automagically (other than uninstalling git). Altough git is desirable, you can use others (Mercurial, subversion, who knows).
* No way to stop createapp from overwriting existing directories.
* CLI also has a bug where if you specify options before unnamed options (such as <name>), it shows unneeded usage information, while the command is running.
* Add options for these, and for overwriting existing directories, abort the operation if the directory exists.
* Fix CLI bug.
(currently not automatically tested, but has been manually tested, we can discuss this and work on more CLI improvements …
=> Improve createapp CLI by adding options

packages/social/src/abstract-provider.service.spec.ts, packages/social/src/abstract-provider.service.ts, packages/social/src/facebook-provider.service.spec.ts, packages/social/src/facebook-provider.service.ts, packages/social/src/google-provider.service.spec.ts, packages/social/src/google-provider.service.ts
=> [Social Auth] Improve social errors.

docs/api-section/openapi-and-swagger-ui.md, docs/api-section/public-api-and-cors-requests.md, docs/api-section/rest-blueprints.md, docs/architecture/controllers.md, docs/architecture/hooks.md, docs/authentication-and-access-control/jwt.md, docs/authentication-and-access-control/password-management.md, docs/authentication-and-access-control/quick-start.md, docs/authentication-and-access-control/session-tokens.md, docs/cookbook/generate-tokens.md, docs/cookbook/limit-repeated-requests.md, docs/databases/generate-and-run-migrations.md, docs/databases/typeorm.md, docs/deployment-and-environments/configuration.md, docs/development-environment/vscode.md, docs/security/csrf-protection.md, docs/tutorials/multi-user-todo-list/2-the-user-and-todo-models.md, docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md, docs/utilities/static-files.md, docs/utilities/templating.md, docs/validation-and-sanitization.md, packages/acceptance-tests/src/examples/cookbook/limit-repeated-requests.spec.ts
It has been five months since version 1 was released. I think we can now reasonably remove comments on version 0.8 from the documentation.
=> [Docs] Remove comments on version 0.8

packages/cli/src/generate/specs/app/config/default.json, packages/cli/src/generate/specs/app/config/default.mongodb.json, packages/cli/src/generate/specs/app/config/default.mongodb.yml, packages/cli/src/generate/specs/app/config/default.yml, packages/cli/src/generate/templates/app/config/default.json, packages/cli/src/generate/templates/app/config/default.mongodb.json, packages/cli/src/generate/templates/app/config/default.mongodb.yml, packages/cli/src/generate/templates/app/config/default.yml, packages/core/src/core/http/http-responses.ts
- Since v4.17.0, ExpressJS has supported the `none` option for the `SameSite` cookie attribute. Developers should be able to use this value.
- Developers using cookies (for example with `@TokenRequired({ cookie: true })`) might not be aware of CSRF attacks and how to protect against them. We should set up a default protection for this in every new project.
=> [CLI] Set default CSRF protection for sessions in the configuration

docs/SUMMARY.md, docs/cookbook/request-body-size.md, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
=> Body parser limit

packages/graphql/package.json
Version 1.3.1 added `type-graphql` by mistake as dependency of the `@foal/graphql` package.
=> [GraphQL] Make TypeGraphQL a dev dep

packages/acceptance-tests/package-lock.json, packages/mongodb/package-lock.json, packages/mongodb/package.json
MongoDB released a new patch version 3.4.
=> [@foal/mongodb] Upgrade MongoDB to v3.4.1

packages/cli/src/generate/generators/app/create-app.ts
The `createapp` command checks the name of the project to see if it fits the (alleged) npm naming conventions. The code is wrong (`@` and `/` are valid for example) and this feature is not really useful.
=> [CLI] Remove wrong npm naming control

packages/cli/src/generate/generators/controller/create-controller.spec.ts, packages/cli/src/generate/generators/controller/register-controller.ts, packages/cli/src/generate/mocks/controller/app.controller.no-import.ts, packages/cli/src/generate/specs/controller/app.controller.controller-import.ts, packages/cli/src/generate/specs/controller/app.controller.empty-property.ts, packages/cli/src/generate/specs/controller/app.controller.empty-spaced-property.ts, packages/cli/src/generate/specs/controller/app.controller.no-import.ts, packages/cli/src/generate/specs/controller/app.controller.rest.ts, packages/cli/src/generate/specs/rest-api/app.controller.controller-import.ts, packages/cli/src/generate/specs/rest-api/app.controller.empty-property.ts, packages/cli/src/generate/specs/rest-api/app.controller.empty-spaced-property.ts, packages/cli/src/generate/specs/rest-api/app.controller.no-controller-import.ts
Resolves #606: when the file `app.controller.ts` does have any imports, the command `foal generate controller --register` fails.
=> [@foal/cli] Fix --register failure when no imports

packages/graphql/package-lock.json, packages/graphql/package.json, packages/graphql/tsconfig.json
As pointed out in #614 and #623, new versions of `graphql` needs the `esnext.asynciterable` lib.
=> Upgrade graphql and modify tsconfig

docs/utilities/static-files.md
The current example does not work, as the forward slash must precede the pathname, not follow it
The path prefix "static/" does not work - content does not load.
The path "/static" works instead.
=> Fix virtual prefix path example

docs/tutorials/multi-user-todo-list/2-the-user-and-todo-models.md, samples/tutorials/02-multi-user-todo-list-mpa/src/app/entities/todo.entity.ts, samples/tutorials/02-multi-user-todo-list-mpa/src/migrations/1581664021032-user-and-todo.ts
Migration fail in multi-user-todo-list tutorial because of todo records not having a user #634
Set Todo.OwnerId field as nullable, update docs and tutorial application
=> fixes #634 - set todo.ownerId field as nullable in tutorial 02

docs/validation-and-sanitization.md, packages/core/src/common/utils/get-ajv-instance.spec.ts, packages/core/src/common/utils/get-ajv-instance.ts
=> [Config] Ajv: support the option allErrors

.github/workflows/test.yml, docs/file-system/local-and-cloud-storage.md, packages/storage/src/index.ts
- `isFileDoesNotExist` is not exported in `@foal/storage`.
- `lerna run test` is a bit slow and, when a test fails in Github Actions, it is difficult to know which one it is.
=> Expose isFileDoesNotExist and improve CI tests

docs/authentication-and-access-control/quick-start.md, docs/authentication-and-access-control/session-tokens.md, docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md, packages/acceptance-tests/src/authentication/session-token.cookie.redirection.spec.ts, packages/acceptance-tests/src/authentication/session-token.cookie.spec.ts, packages/acceptance-tests/src/authentication/session-token.token.spec.ts, packages/acceptance-tests/src/mongoose-db.mongodb-store.spec.ts, packages/acceptance-tests/src/mongoose-db.redis-store.spec.ts, packages/core/src/sessions/session-store.spec.ts, packages/core/src/sessions/session.spec.ts, packages/core/src/sessions/session.ts, packages/core/src/sessions/token.hook.spec.ts, packages/core/src/sessions/token.hook.ts, packages/csrf/src/csrf-token-required.hook.spec.ts, packages/csrf/src/get-csrf-token.util.spec.ts, packages/mongodb/src/mongodb-store.service.spec.ts, packages/mongodb/src/mongodb-store.service.ts, packages/redis/src/redis-store.service.spec.ts, packages/redis/src/redis-store.service.ts, packages/typeorm/src/typeorm-store.service.spec.ts, packages/typeorm/src/typeorm-store.service.ts
**Version 2**
Logging users out in Foal is not simple and intuitive. This PR reduces the amount of code to be produced and makes it clearer.
**Before**
```typescript
import {
dependency, Context, HttpResponseNoContent, Post,
Session, TokenRequired
} from '@foal/core';
import { TypeORMStore } from '@foal/typeorm';
export class AuthController {
@dependency
store: TypeORMStore;
@Post('/logout')
@TokenRequired({
extendLifeTimeOrUpdate: false,
store: TypeORMStore,
})
async logout(ctx: Context<any, Session>) {
await this.store.destroy(ctx.session.sessionID);
return new HttpResponseNoContent();
}
}
```
**After**
```typescript
import {
Context, HttpResponseNoContent, Post, TokenOptional
} from '@foal/core';
import { TypeORMStore } from '@foal/typeorm';
export class AuthController { …
```
=> [V2] [Sessions] Simplify logout

docs/architecture/services-and-dependency-injection.md, packages/acceptance-tests/src/examples/architecture/services-and-dependency-injection.spec.ts, packages/core/src/core/index.ts, packages/core/src/core/service-manager.spec.ts, packages/core/src/core/service-manager.ts
=> [Dependency injection] Support interface and generic classes injection

docs/authentication-and-access-control/jwt.md, packages/jwt/src/jwt.hook.spec.ts, packages/jwt/src/jwt.hook.ts
=> Support other character encodings for JWT secrets

.github/workflows/test.yml, docker-compose.yml, docs/authentication-and-access-control/groups-and-permissions.md, packages/typeorm/src/entities/group.entity.spec.ts, packages/typeorm/src/entities/group.entity.ts, packages/typeorm/src/entities/permission.entity.spec.ts, packages/typeorm/src/entities/permission.entity.ts, packages/typeorm/src/entities/user-with-permissions.entity.spec.ts, packages/typeorm/src/entities/user-with-permissions.entity.ts
=> UserWithPermissions extends BaseEntity and new UserWithPermissions.withPerm static method

docs/SUMMARY.md, docs/architecture/initialization.md, packages/core/src/core/service-manager.spec.ts, packages/core/src/core/service-manager.ts
=> Support service initialization (boot method) 

e2e_test.sh, packages/core/package-lock.json, packages/core/package.json, packages/core/src/core/http/contexts.ts, packages/core/src/core/http/mime.d.ts, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts, packages/core/src/express/create-middleware.spec.ts, packages/core/src/express/create-middleware.ts, packages/core/src/express/express.d.ts, packages/core/src/express/handle-errors.ts, packages/core/src/express/not-found.ts, packages/core/src/express/send-response.ts
Fixes #683 
Some changes have been brought in a *patch* version to `@types/express` causing some parts of the framework to break (i.e. `foal g rest-api`).
This is not the first time it happens, so the idea is to fix `@types/express` to a specific version.
Unfortunately, this cannot be done because `@types/express` requires version `*` of `@types/express-serve-static-core`. So going back to an old version of `@types/express` cannot work.
So we have to use `@types/express-serve-static-core` directly.
=> Fix @types/express types problems

packages/cli/src/generate/generators/model/create-model.spec.ts, packages/cli/src/generate/generators/model/create-model.ts, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/src/app/models/index.ts, packages/cli/src/generate/specs/app/src/app/models/user.model.ts, packages/cli/src/generate/specs/model/index.sorted.ts, packages/cli/src/generate/specs/model/index.ts, packages/cli/src/generate/specs/model/test-foo-bar.model.ts, packages/cli/src/generate/templates/app/package.mongodb.json, packages/cli/src/generate/templates/app/package.mongodb.yaml.json, packages/cli/src/generate/templates/app/src/app/models/index.ts, packages/cli/src/generate/templates/app/src/app/models/user.model.ts, packages/cli/src/generate/templates/model/model.ts, packages/mongodb/package-lock.json, packages/mongodb/package.json, packages/mongodb/src/mongodb-store.service.spec.ts, packages/mongodb/src/mongodb-store.service.ts, packages/mongodb/src/mongodb.d.ts, packages/mongoose/package-lock.json, packages/mongoose/package.json, packages/mongoose/src/utils/fetch-user.util.spec.ts, packages/mongoose/src/utils/fetch-user.util.ts, packages/mongoose/src/utils/mongoose.d.ts
Fixes #687.
A recent change on the `@types/mongodb` package made the build to fail. We had a lot of these issues in the past with different `@types` packages.
To fix this, `@types/mongodb` and `@types/mongoose` are removed from `@foal` packages. This introduces some `any` in function parameters or return values but does not add breaking changes (`any` can be assigned to anything and anything can be assign to `any`).
People using Foal still have the possibility to install `@types/mongodb` and `@types/mongoose` if they want to use them.
=> Remove mongoose types

docs/tutorials/mongodb-todo-list/3-the-todo-model.md, packages/acceptance-tests/src/error-handling.spec.ts, packages/core/package-lock.json, packages/core/package.json, packages/core/src/core/http/contexts.ts, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts, packages/core/src/express/create-middleware.spec.ts, packages/core/src/express/create-middleware.ts, packages/core/src/express/express.d.ts, packages/core/src/express/handle-errors.spec.ts, packages/core/src/express/handle-errors.ts, packages/core/src/express/not-found.ts, packages/core/src/express/send-response.spec.ts, packages/core/src/express/send-response.ts, packages/core/src/sessions/token.hook.ts, packages/formidable/package-lock.json, packages/formidable/package.json, packages/formidable/src/parse-form.spec.ts, packages/formidable/src/parse-form.ts, packages/jwt/src/jwt.hook.ts
Fixes #686 
As `@types/express` requires any `*` version of `@types/express-serve-static-core` we are stuck. We cannot go back to `@types/express@4.17.2` because it will requires the latest version of `@types/express-serve-static-core` which is incompatible with v4.17.2.
Remove `@types/express-serve-static-core` from `@foal/core` and define manually the interface of `Context.request` (based on Node.js and Express documentation, `@types/node` and the old `@types/express-serve-static-core`). This will unfortunately turn some types into `any` but it should not add any breaking changes.
=> Fix Express types

docs/architecture/controllers.md, packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/cli/src/generate/templates/app/package.mongodb.yaml.json, packages/cli/src/generate/templates/app/package.yaml.json, packages/core/src/express/create-middleware.spec.ts, packages/core/src/express/create-middleware.ts, packages/core/src/sessions/session.ts
Resolves #507 .
Also fixes bug #706.
The request body and path parameters are now also passed as third and second arguments to the controller methods.
```typescript
// Product is here a class validator in this example.
// before
class AppController {
@Put('/products/:id')
@ValidateBody(Product)
updateProduct(ctx: Context) {
const id = ctx.request.params.id;
const body = ctx.request.body as Product;
// Do something.
}
}
// after
class AppController {
@Put('/products/:id')
@ValidateBody(Product)
updateProduct(ctx: Context, { id }, body: Product) {
// Do something.
}
}
```
=> Pass request body and path parameters as third and second arguments to the controller methods

docs/authentication-and-access-control/session-tokens.md, packages/core/package.json, packages/core/src/sessions/token-optional.hook.ts, packages/core/src/sessions/token-required.hook.ts, packages/core/src/sessions/token.hook.spec.ts, packages/core/src/sessions/token.hook.ts, packages/internal-test/src/index.ts, packages/mongodb/src/index.ts, packages/redis/src/index.ts, packages/storage/src/disk.service.spec.ts, packages/storage/src/disk.service.ts, packages/typeorm/src/index.ts
=> [Sessions] Allow to specify the store name in a configuration file

docs/architecture/initialization.md, e2e_test.sh, packages/acceptance-tests/src/mongoose-db.mongodb-store.spec.ts, packages/acceptance-tests/src/mongoose-db.redis-store.spec.ts, packages/acceptance-tests/src/typeorm.mongodb-store.spec.ts, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts, packages/mongodb/src/mongodb-store.service.spec.ts, packages/mongodb/src/mongodb-store.service.ts, packages/redis/src/redis-store.service.spec.ts, packages/redis/src/redis-store.service.ts
Services can be initialized using their `boot` method. For this to work, we currently need to call `ServicesManager.boot()` in `src/index.ts`.
In version 2, this feature is enabled by default. No need to call `ServicesManager.boot()` anymore.
If you use the `boot` feature, remove the `ServiceManager.boot()` call from `src/index.ts`
If you do not use the `boot` feature, the property `boot` in every service/controller is now a reserved keyword (cf service initialization).
=> [V2] Initialize services by default

docs/authentication-and-access-control/quick-start.md, docs/authentication-and-access-control/session-tokens.md, packages/acceptance-tests/src/authentication/session-token.cookie.redirection.spec.ts, packages/acceptance-tests/src/authentication/session-token.cookie.spec.ts, packages/acceptance-tests/src/authentication/session-token.token.spec.ts, packages/acceptance-tests/src/authorization/groups-and-permissions.spec.ts, packages/acceptance-tests/src/csrf/regular-web-app.stateful.spec.ts, packages/acceptance-tests/src/csrf/spa-and-api.stateful.spec.ts, packages/typeorm/src/index.ts, packages/typeorm/src/typeorm-store.service.spec.ts, packages/typeorm/src/typeorm-store.service.ts
Resolves #766 
- All users will be logged out when upgrading to v2.
- The session table must be created with migrations. A migration file can be created from `DatabaseSession`.
- The old `foal_session` table can be manually removed.
=> [V2][Sessions] Do not let TypeORMStore auto-update the database schema.

docs/authentication-and-access-control/session-tokens.md, packages/core/src/sessions/session-store.spec.ts, packages/core/src/sessions/session-store.ts, packages/core/src/sessions/session.spec.ts, packages/core/src/sessions/session.ts, packages/core/src/sessions/token.hook.spec.ts, packages/core/src/sessions/token.hook.ts, packages/csrf/src/csrf-token-required.hook.spec.ts, packages/csrf/src/get-csrf-token.util.spec.ts, packages/mongodb/package.json, packages/mongodb/src/mongodb-store.service.spec.ts, packages/mongodb/src/mongodb-store.service.ts, packages/redis/package.json, packages/redis/src/redis-store.service.spec.ts, packages/redis/src/redis-store.service.ts, packages/typeorm/src/typeorm-store.service.spec.ts, packages/typeorm/src/typeorm-store.service.ts
Resolves #510.
Resolves #778.
Resolves #779.
- Interface of the `Session` constructor.
- `TypeORMStore` only support numbers (not strings) as user IDs.
- The `userId` is not stored in the session content.
- Redis session key now starts with `sessions:` instead of `session:`.
- MongoDB collection is now named `sessions` instead of `foalSessions`.
When migrating to v2, all users will be logged out.
When migrating to v2 (optional) :
- remove the old TypeORM table,
- remove the old  MongoDB `foalSessions` collection.
=> [V2] Officially support authenticated sessions and allow to perform certain actions on them.

packages/typestack/src/validate-body.hook.spec.ts, packages/typestack/src/validate-body.hook.ts
Fixes #785
I'm not sure what the target branch should be
=> Fix typestack validateBody hook

docs/authentication-and-access-control/session-tokens.md, packages/mongodb/src/mongodb-store.service.spec.ts, packages/mongodb/src/mongodb-store.service.ts
=> [MongoStore] Use sessionID instead of _id

packages/core/src/openapi/create-open-api-document.spec.ts, packages/core/src/openapi/create-open-api-document.ts
Regex used to test for duplicate paths uses greedy matching causing valid RESTful hierarchy to be
flagged as an error:
fix #821
=> fix(SwaggerValidation): Allow hierarchy in paths

.github/CONTRIBUTING.MD, docs/README.md, packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.ts, packages/cli/src/generate/templates/rest-api/controller.ts
I used the rest-api command yesterday and I saw those deprecation warnings.
=> fix rest-api deprecations

packages/cli/src/generate/specs/app/public/index.html, packages/cli/src/generate/templates/app/public/index.html, packages/core/src/common/utils/500.debug.html, packages/core/src/common/utils/render-error.util.spec.ts, packages/core/src/common/utils/render-error.util.ts
The welcome page (when creating a new project) and the debugging page (when a 500 error is thrown) are not very nice. This PR makes them prettier.
This debug page displays also more information (file name and numbers of the row and the column).
*Before*
*After*
*Before*
*After*
=> Pretiffy the welcome and the "500 error" pages

e2e_test.sh, packages/cli/src/index.ts
When a CLI command fails and displays an error, the exit code is still 0. This is annoying when using commands in a CI because the pipeline is not notified.
Exit with code 1 when a command fails
=> Make CLI exit with code 1 when a command fails.

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json
Keep up-to-date with docusaurus alpha versions.
=> [Docs] Update docusaurus dependencies to alpha 70

packages/cli/src/generate/generators/app/create-app.ts
=> Hide unhelpful sqlite3 warnings when using createapp with npm

docs/docs/security/csrf-protection.md, packages/acceptance-tests/src/common/index.ts, packages/acceptance-tests/src/common/typeorm-store.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/administrators-and-roles/controlling-access-with-administrators.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/administrators-and-roles/controlling-access-with-static-roles.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/common/index.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateful-spa-using-cookies.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateful-spa-using-header.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateful-ssr-app-using-cookies.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/adding-authentication-and-access-control.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/destroying-the-session.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/do-not-auto-create-the-session.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/modifying-session-timeouts.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/overriding-the-cookie-options.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/reading-a-session-from-a-token.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/requiring-the-session-cookie.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/revoking-sessions.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/saving-and-reading-content.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/using-cookies.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/using-the-authorization-header.feature.ts, packages/acceptance-tests/src/docs/security/csrf/disabling-csrf-protection-on-a-specific-route.feature.ts, packages/core/src/sessions/use-sessions.hook.spec.ts, packages/core/src/sessions/use-sessions.hook.ts, packages/jwt/src/jwt.hook.spec.ts, packages/jwt/src/jwt.hook.ts
=> Allow to disable the CSRF protection on a specific route

packages/cli/src/generate/specs/app/src/index.ts, packages/cli/src/generate/templates/app/src/index.ts, packages/core/src/common/utils/display-server-url.util.spec.ts, packages/core/src/common/utils/display-server-url.util.ts, packages/core/src/common/utils/index.ts, packages/core/src/index.ts, packages/examples/src/index.ts
This PR makes prettier the output of the server when it starts.
*Before*
*Output*
=> Prettify server output

docs/docs/architecture/hooks.md, docs/docs/authentication-and-access-control/password-management.md, docs/docs/cookbook/base64url.md, docs/i18n/es/docusaurus-plugin-content-docs/current/architecture/hooks.md, docs/i18n/es/docusaurus-plugin-content-docs/current/authentication-and-access-control/password-management.md, docs/i18n/es/docusaurus-plugin-content-docs/current/cookbook/base64url.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/architecture/hooks.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/authentication-and-access-control/password-management.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/cookbook/base64url.md, docs/sidebars.js, packages/acceptance-tests/src/additional/authentication/do-not-save-sessions-on-error.spec.ts, packages/acceptance-tests/src/docs/architecture/hooks/forwarding-data-between-hooks.feature.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/regenerating-the-session-id.feature.ts, packages/cli/src/generate/generators/rest-api/create-rest-api.spec.ts
This PR add some parts that were missing in the documentation. It also some more tests to the framework.
=> Add missing documentation and add more e2e tests

docs/docs/architecture/controllers.md, docs/i18n/es/docusaurus-plugin-content-docs/current/architecture/controllers.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/architecture/controllers.md
I was reading the docs when i found this little typo
=> fix typo in controllers docs

docs/blog/version-2.3-release-notes.md, docs/docs/common/conversions.md, docs/docs/cookbook/base64url.md, docs/i18n/es/docusaurus-plugin-content-docs/current/common/conversions.md, docs/i18n/es/docusaurus-plugin-content-docs/current/cookbook/base64url.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/common/conversions.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/cookbook/base64url.md, docs/sidebars.js, packages/aws-s3/src/s3-disk.service.spec.ts, packages/core/src/common/encoding/convert-base64-to-base64-url.spec.ts, packages/core/src/common/encoding/convert-base64-to-base64-url.ts, packages/core/src/common/encoding/convert-base64-url-to-base64.spec.ts, packages/core/src/common/encoding/convert-base64-url-to-base64.ts, packages/core/src/common/encoding/index.ts, packages/core/src/common/index.ts, packages/core/src/common/tokens/generate-token.util.ts, packages/core/src/common/tokens/index.ts, packages/core/src/common/tokens/sign-token.util.ts, packages/core/src/common/utils/index.ts, packages/core/src/common/utils/stream-to-buffer.spec.ts, packages/core/src/common/utils/stream-to-buffer.ts, packages/core/src/index.ts, packages/graphiql/src/graphiql.controller.spec.ts, packages/jwt/src/jwt.hook.spec.ts, packages/storage/src/local-disk.service.spec.ts, packages/storage/src/validate-multipart-form-data-body.hook.ts, packages/swagger/src/swagger-controller.spec.ts
- The conversion utility `convertBase64ToBase64url` has no "reverse equivalent".
- In many parts of the framework (especially in tests), readable streams are converted to buffers. Duplicate code could be avoided here.
=> Add "streamToBuffer" and "convertBase64urlToBase64" functions

.github/workflows/test.yml, packages/social/src/abstract-provider.service.spec.ts, packages/social/src/abstract-provider.service.ts
=> [V1] [Social] Fix state bad URL characters

docs/docs/common/validation-and-sanitization.md, packages/core/src/common/utils/get-ajv-instance.spec.ts, packages/core/src/common/utils/get-ajv-instance.ts
Add support for the AJV $data option to Foal configuration. Resolves #920
=> AJV $data support #920

docs/docs/authentication-and-access-control/groups-and-permissions.md, docs/i18n/es/docusaurus-plugin-content-docs/current/authentication-and-access-control/groups-and-permissions.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/authentication-and-access-control/groups-and-permissions.md, docs/i18n/id/docusaurus-plugin-content-docs/current/authentication-and-access-control/groups-and-permissions.md, packages/cli/src/generate/specs/app/src/scripts/create-user.ts, packages/cli/src/generate/templates/app/src/scripts/create-user.ts
The default `create-user` script generated by `createapp` has a lot of commented code that can be "intimidating" and is eventually not very useful. This PR removes the commented lines about groups and permissions and moves them to the documentation.
=> [CLI] Simplify default create-user script

packages/core/src/common/utils/render-error.util.spec.ts, packages/core/src/common/utils/render-error.util.ts
=> Fix renderError error

docs/docs/api-section/openapi-and-swagger-ui.md, docs/i18n/es/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md, docs/i18n/id/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
Mini typo in openapi docs
Add required field "description" to ApiResponse decorator in code example.
=> Fix typo in openapi docs

docs/docs/file-system/upload-and-download-files.md, docs/i18n/es/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md, docs/i18n/id/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md, packages/storage/src/disk.service.spec.ts, packages/storage/src/disk.service.ts
=> Add cache option to Disk.createHttpResponse 

docs/docs/architecture/controllers.md, packages/core/src/core/http/http-responses.spec.ts, packages/core/src/core/http/http-responses.ts
I have a monorepo where I am using Foal for the backend and have a different project for the frontend. Since the type of `body` is `any`, I can't make any guarantees around what that data should look like.
```typescript
export class TodosController {
@Get('/')
getTodos() {
return new HttpResponseOK(this.todoService.getTodos())
}
}
```
and the frontend would have to read it like this:
```typescript
const response = await fetch('/todos')
if (response.ok) {
// Here I'm just assuming that the backend is returning an array of todos
const todos: Todo[] = await response.json()
/*
Alternatively, an additional validation step would be necessary to be safe:
const maybeTodos = await response.json()
if (isTodos(maybeTodos)) {
return maybeTodos
}
*/
return todos
}
```
By making the `body` generic, I …
=> Make body generic on HttpResponse

docs/blog/version-2.7-release-notes.md, docs/docs/architecture/configuration.md, docs/docs/deployment-and-environments/checklist.md, packages/core/src/core/config/config.spec.ts, packages/core/src/core/config/config.ts, packages/core/src/core/config/env.spec.ts, packages/core/src/core/config/env.ts
=> Allow to use FOAL_ENV to define the environment name

packages/cli/package.json
https://github.com/Marak/colors.js/issues/285
Lock the version to 1.4.0 to prevent installing the breaking version
=> Color js Bug Fix

docs/blog/version-2.8-release-notes.md, docs/docs/authentication-and-access-control/session-tokens.md, packages/acceptance-tests/src/common/create-test-connection.ts, packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/providing-a-custom-client-to-use-in-stores.feature.ts, packages/mongodb/src/mongodb-store.service.spec.ts, packages/mongodb/src/mongodb-store.service.ts, packages/redis/src/redis-store.service.spec.ts, packages/redis/src/redis-store.service.ts, packages/typeorm/src/typeorm-store.service.spec.ts, packages/typeorm/src/typeorm-store.service.ts
Resolves issue described in #1017
It also avoids to have multiple connections to redis in the app if redis is used somewhere else.
=> Allow to pass a custom client/connection to redis, MongoDB and TypeORM stores.

.github/workflows/test.yml, docs/docs/file-system/local-and-cloud-storage.md, packages/aws-s3/config/default.json, packages/aws-s3/package-lock.json, packages/aws-s3/package.json, packages/aws-s3/src/s3-disk.service.spec.ts, packages/aws-s3/src/s3-disk.service.ts, packages/storage/src/disk.service.ts, packages/storage/src/local-disk.service.ts, packages/storage/src/validate-multipart-form-data-body.hook.ts
- Upgrade all major versions for v3.
- Reduce `node_modules/` size.
Related PR: #914
- All `Disk.write` take a `Readable` as parameter and not a `NodeJS.ReadableStream` anymore.
- The AWS region must be provided to connect to S3.
=> Upgrade from `aws-sdk@2` to `@aws-sdk/client-s3@3`

packages/cli/src/generate/generators/app/create-app.ts
The creation of a new project (i.e. `createapp`) on Node 10 with yarn is failing: https://github.com/FoalTS/foal/actions/runs/2107640821.
Underlying reason: a sub-dependency of a direct dependency requires at least Node v12.
Issue: v2 of Foal still officially supports Node 10 (which is not maintained anymore), so the unique option here is not to check this value in the package.json (which is not great but ok for the situation).
For future major versions of Foal: the minimum version of NodeJS required should always be recent (at least v14 for Foal v3).
Do no check the `engine` in yarn installation .
Similar commit: https://github.com/FoalTS/foal/commit/91414f1fd497040595e13d38479f584c1d8360f1
=> [CLI] Fix installation with yarn on node 10

.github/workflows/test.yml, packages/aws-s3/src/s3-disk.service.spec.ts, packages/jwks-rsa/package-lock.json, packages/social/package-lock.json, packages/social/package.json, packages/social/src/abstract-provider.service.ts, packages/social/src/facebook-provider.service.ts, packages/social/src/github-provider.service.ts, packages/social/src/linkedin-provider.service.ts, packages/social/typings/node-fetch/index.d.ts
We cannot upgrade the `node-fetch` dependency to `node-fetch@3` because it requires ESM enabled. For this reason, we had to remove the dependency to use another one (building, testing and maintaining a http client was requiring too much work). I chose `axios`.
Pros: it is widely used and has only one dependency.
Cons: it is still in `0.x.y`.
=> Replace `node-fetch` with `axios`

docs/docs/authentication-and-access-control/groups-and-permissions.md
Syntax error in docs for auth and access control.
Removed semi colon, see file change.
=> [Docs] Syntax error fix

docs/docs/api-section/graphql.md, packages/graphql/package-lock.json, packages/graphql/package.json
Resolves #1066
The `@foal/graphql` package only supports version 14 of `graphql` but recent versions of `type-graphql` requires version 15.
=> Support `graphql@15`

docs/docs/authentication-and-access-control/social-auth.md, packages/examples/config/default.yml, packages/examples/ormconfig.json, packages/examples/src/app/controllers/auth.controller.ts, packages/examples/src/app/entities/user.entity.ts, packages/examples/src/migrations/1651699145020-sessions.ts, packages/examples/templates/signin.html, packages/social/src/abstract-provider.service.spec.ts, packages/social/src/abstract-provider.service.ts, packages/social/src/index.ts, packages/social/src/twitter-provider.service.spec.ts, packages/social/src/twitter-provider.service.ts
#1014
#1047 
Two more optional configs were added in AbstractProvider: 
- useCodeChallenge (boolean): to enable Code Flow
- codeChallengeMethodPlain (boolean): to force plain method instead SHA256
if it's enable then redirect() set a new Cookie with code_challenge to send as code_verifier parameter when fetch token and add to authorize url path both code_challenge and code_challenge_method
With this new approach then added TwitterProvider using this new feature to interact with twitter api.
Tests added to Abstract Provider
-  has a "redirect" method that
- should return an HttpResponseRedirect object
- if code_challenge is configured as active in config
✓ with code_challenge_method (S256) - codeChallengeMethodPlain: false
✓ with code_challenge_method (plain) - codeChallengeMethodPlain: …
=> Add PKCE and Twitter provider - #1014 #1047

packages/cli/src/generate/specs/app/src/app/entities/user.entity.mongodb.ts, packages/cli/src/generate/specs/app/src/app/entities/user.entity.ts, packages/cli/src/generate/specs/app/src/scripts/create-user.mongodb.ts, packages/cli/src/generate/specs/app/src/scripts/create-user.ts, packages/cli/src/generate/specs/script/test-foo-bar.ts, packages/cli/src/generate/templates/app/src/app/entities/user.entity.mongodb.ts, packages/cli/src/generate/templates/app/src/app/entities/user.entity.ts, packages/cli/src/generate/templates/app/src/scripts/create-user.mongodb.ts, packages/cli/src/generate/templates/app/src/scripts/create-user.ts, packages/cli/src/generate/templates/script/script.ts
- Generated files are often coupled with TypeORM.
- There are a lot of comments that go against the "simplicity" value of the framework.
See solutions and steps.
=> Simplify generated CLI files and do not make shell scripts depend on TypeORM

docs/docusaurus.config.js, docs/src/pages/index.jsx, package.json, packages/core/package.json
FoalTS survey 2022 (which I am still reviewing) has highlighted some points that a majority of users like. The website should show these points at the beginning of the landing page.
=> [Website] Update landing page based on FoalTS survey 2022

docs/docs/authentication-and-access-control/administrators-and-roles.md
grammar was incorrect and created slight confusion
corrected the grammar
- [ *] Add/update/check docs (code comments and docs/ folder).
- [ *] Add/update/check tests.
- [ *] Update/check the cli generators.
=> [Docs] correct grammar `administrators-and-roles` doc

packages/core/src/sessions/http/get-session-id-from-request.spec.ts, packages/core/src/sessions/http/get-session-id-from-request.ts, packages/core/src/sessions/use-sessions.hook.ts, packages/jwt/src/http/get-jwt-from-request.spec.ts, packages/jwt/src/http/get-jwt-from-request.ts, packages/jwt/src/jwt.hook.ts
`@JWT` and `@UseSessions` are big functions with a lot of tests. It is hard to add new features to them without providing a lot of work.
=> [Cleanup] Move http request read from `@JWT` and `@UseSessions` into separate functions

packages/typeorm/src/entities/user-with-permissions.entity.spec.ts, packages/typeorm/src/entities/user-with-permissions.entity.ts
The `fetchUserWithPermissions` function will be removed. We need a quick function to replace it.
- `User.findOneWithPermissionsBy` has been added.
=> Add `User.findOneWithPermissionsBy`

packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/cli/src/generate/templates/app/package.mongodb.yaml.json, packages/cli/src/generate/templates/app/package.yaml.json
- When running the npm run build command locally, the foal binary is found because we have previously installed it globally using npm install -g @foal/cli . So the command works.
- But when deploying to a PaaS provider (such a Heroku), the command fails because the CLI has not been installed globally. Only dependencies specified in package.json are installed.
Added the @foal/cli of version 2.9.0 to the package.json templates in the folders:
- <ROOT>\packages\cli\src\generate\templates\app
- <ROOT>\packages\cli\src\generate\specs\app
To test this, set up the environment as stated in the Contributing Guidelines. You don't have to setup the Database, so skip the docker-start command.
1. After setup, go to the folder "packages\cli\lib"
2. run the following command:
`node index.js createapp -G …
=> Adds @foal/cli to package.json templates

packages/cli/src/generate/file-system.spec.ts, packages/cli/src/generate/file-system.ts
If we ever want to have an notifier that displays a message when updates to Foal have been released, we will need access to the project dependencies.
=> Add `fs.getProjectDependencies` and `fs.getProjectDevDependencies`

packages/core/src/core/config/config.spec.ts, packages/core/src/core/config/config.ts
Resolves #1071
`undefined` values do not override other defined config values anymore.
=> Do not let "undefined" values override other config values

packages/core/src/core/http/context.ts, packages/core/src/core/http/http-responses.ts, packages/core/src/sessions/session-store.ts, packages/jwt/src/invalid-token.error.ts, packages/socket.io/src/architecture/websocket-context.ts, packages/storage/src/disk.service.ts
Some class properties have should be `readonly`
`Context.request`, `Context.state`, `HttpResponse.statusCode`, `HttpResponse.statusMessage`, `WebsocketContext.socket` and `WebsocketContext.state` are readonly.
=> Be stricter on some class properties accessors. 

docs/docs/cookbook/limit-repeated-requests.md, docs/docs/websockets.md, packages/acceptance-tests/src/docs/cookbook/limit-repeated-requests.spec.ts, packages/cli/src/generate/specs/app/src/index.ts, packages/cli/src/generate/templates/app/src/index.ts, packages/examples/src/index.ts
In `src/index.ts`, we use the `http.createServer` method. This makes noise and is not necessary. This can be simplified by simply calling `app.listen`
=> [CLI] Remove use of `http` module from app bootstrap

README.md, docs/docs/README.md, docs/docs/api-section/gRPC.md, docs/docs/api-section/graphql.md, docs/docs/development-environment/build-and-start-the-app.md, docs/docs/development-environment/create-and-run-scripts.md, docs/docs/tutorials/real-world-example-with-react/1-introduction.md, docs/docs/tutorials/real-world-example-with-react/14-production-build.md, docs/docs/tutorials/simple-todo-list/1-installation.md, packages/cli/src/generate/generators/app/create-app.ts, packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/cli/src/generate/templates/app/package.mongodb.yaml.json, packages/cli/src/generate/templates/app/package.yaml.json, packages/cli/src/run-script/run-script.spec.ts, packages/cli/src/run-script/run-script.ts, packages/examples/package.json
Small improvement whose goals are:
- smaller command
- be consistent with the command of other frameworks
The command `npm run develop` has been renamed to `npm run dev`
=> Rename "npm run develop" to "npm run dev"

packages/storage/src/disk.service.spec.ts, packages/storage/src/disk.service.ts, packages/storage/src/local-disk.service.ts
When downloading a file, some navigators (might) need to always have the `Content-Type` header defined.
- Add `application/octet-stream` as default `Content-Type` header.
=> Add default `Content-Type` header in `Disk.createHttpResponse` responses

packages/core/src/sessions/http/get-csrf-token-from-request.spec.ts, packages/core/src/sessions/http/get-csrf-token-from-request.ts, packages/core/src/sessions/http/use-sessions.hook.spec.ts, packages/core/src/sessions/http/use-sessions.hook.ts, packages/jwt/src/http/get-csrf-token-from-request.spec.ts, packages/jwt/src/http/get-csrf-token-from-request.ts, packages/jwt/src/jwt.hook.spec.ts, packages/jwt/src/jwt.hook.ts
The `@UseSessions` and `@JWT` hooks do too much stuff and so the tests are difficult to maintain and modify.
=> Add `getCsrfTokenFromRequest` util

packages/core/src/sessions/http/use-sessions.hook.spec.ts, packages/core/src/sessions/http/use-sessions.hook.ts, packages/core/src/sessions/http/utils/index.ts, packages/core/src/sessions/http/utils/should-verify-csrf-token.spec.ts, packages/core/src/sessions/http/utils/should-verify-csrf-token.ts, packages/jwt/src/http/jwt.hook.spec.ts, packages/jwt/src/http/jwt.hook.ts, packages/jwt/src/http/utils/get-csrf-token-from-cookie.spec.ts, packages/jwt/src/http/utils/get-csrf-token-from-cookie.ts, packages/jwt/src/http/utils/index.ts, packages/jwt/src/http/utils/should-verify-csrf-token.spec.ts, packages/jwt/src/http/utils/should-verify-csrf-token.ts
The `@UseSessions` and `@JWT` hooks do too much stuff and so the tests are difficult to maintain and modify.
=> Add `getCsrfTokenFromCookie` and `shouldVerifyCsrfToken` utils

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json
Some searches on Google redirect users to the version 1 of the documentation which is deprecated. Only v2 pages should be indexed on Google.
=> [Docs] Do not index v1 documentation on Google

packages/social/package-lock.json, packages/social/package.json, packages/social/src/abstract-provider.service.ts, packages/social/src/facebook-provider.service.ts, packages/social/src/github-provider.service.ts, packages/social/src/linkedin-provider.service.ts, packages/social/src/twitter-provider.service.ts, packages/social/typings/node-fetch/index.d.ts
In v3, we changed the `node-fetch` dependency to `axios` in `@foal/social` (#1056). The reason behind this is that we couldn't upgrade `node-fetch` to `node-fetch@3` because it was requiring ES modules.
Since `fetch` is available since Node 18, we will just remove the dependency when the support of Node 16 is dropped in Foal. In this way, we don't need to change anything in the package for now and so we don't need to do a manual test before releasing v3.
=> Revert dependency change in @foal/social

docs/docs/authentication-and-access-control/session-tokens.md, docs/docs/upgrade-to-v3/README.md, packages/typeorm/src/typeorm-store.service.spec.ts, packages/typeorm/src/typeorm-store.service.ts
There is a pending PR (#1142) that will add the same methods for MongoDB. As in Mongo, there might be two IDs (`_id` an d `id`), it becomes complicated to pass the user object. 
- Make `TypeORMStore.getSessionIDsOf` and `TypeORMStore.destroyAllSessionsOf` the user ID as parameter.
- `TypeORMStore.getSessionIDsOf` and `TypeORMStore.destroyAllSessionsOf` no longer take the user object as parameter but the user ID.
=> Homogenize `getSessionIDsOf` and `destroyAllSessionsOf` methods of all stores

docs/docs/api-section/graphql.md, packages/graphql/src/graphql.controller.ts
In new version of GraphiQL, if the operation name is not defined, the browser stills send a `operationName` property with `null` as value. This case is not supported and the server responds with a 400 status.
=> Make GraphQLController with new version of GraphiQL

docs/docs/cookbook/limit-repeated-requests.md, docs/docs/security/http-headers-protection.md, docs/i18n/es/docusaurus-plugin-content-docs/current/cookbook/limit-repeated-requests.md, docs/i18n/es/docusaurus-plugin-content-docs/current/security/http-headers-protection.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/cookbook/limit-repeated-requests.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/security/http-headers-protection.md, docs/i18n/id/docusaurus-plugin-content-docs/current/cookbook/limit-repeated-requests.md, docs/i18n/id/docusaurus-plugin-content-docs/current/security/http-headers-protection.md, docs/versioned_docs/version-1.x/cookbook/limit-repeated-requests.md, docs/versioned_docs/version-1.x/security/http-headers-protection.md, packages/acceptance-tests/src/docs/cookbook/limit-repeated-requests.spec.ts, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts
Resolves #1146.
max-age in the Strict-Transport-Security header is set to 15552000 (1 year) but this is better set to 31536000 (2 years) according to multiple security best practice sources.
Change value from 15552000 to 31536000 across codebase
=> Changed max-age of Strict-Transport-Security header

packages/acceptance-tests/package-lock.json, packages/acceptance-tests/package.json, packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/cli/src/generate/templates/app/package.mongodb.yaml.json, packages/cli/src/generate/templates/app/package.yaml.json, packages/examples/package-lock.json, packages/examples/package.json, packages/typeorm/package-lock.json, packages/typeorm/package.json
- The TypeORM dependency needs to be updated (more recent version available)
- They are some inconsistencies between peer dependencies and versions installed by `createapp` causing the npm install to fail.
=> Update TypeORM version and fix peer dependency issue

docs/docusaurus.config.js, docs/src/pages/who-is-using-foal.jsx
=> Add empty "Who's using Foal?" page

docs/docs/tutorials/real-world-example-with-react/9-authenticated-api.md
Add casting to prevent build error:
```
stories.controller.ts:47:5 - error TS2322: Type '{ [key: string]: any; } | null' is not assignable to type 'User'.
Type 'null' is not assignable to type 'User'.
47     story.author = ctx.user;
````
Maybe there is a better way to fix this?
```
$ npm run build
src/app/controllers/api/stories.controller.ts:47:5 - error TS2322: Type '{ [key: string]: any; } | null' is not assignable to type 'User'.
Type 'null' is not assignable to type 'User'.
47     story.author = ctx.user;
~~~~~~~~~~~~
47     story.author = ctx.user;
````
Add casting
=> docs(update) Fix issue in auth user code example

packages/cli/src/generate/specs/app/.eslintrc.js, packages/cli/src/generate/templates/app/.eslintrc.js
When following the second tutorial, we get an ESLint warning with the IDE on statements such as `ctx.session!`. This PR removes this warning to not confuse people following the tutorial.
=> Adapt generated eslint config to support ctx.session!

.github/workflows/daily-test.yml, .github/workflows/test.yml, e2e_test.sh
When using PM2, we get failures in the CI with a "exit code 7". This is not the first time it happens and I don't understand what the issue is.
=> Remove pm2 to fix CLI failure

packages/core/src/core/config/env.spec.ts, packages/core/src/core/config/env.ts
=> Support whitespaces around variable names in `.env` files

docs/blog/version-3.1-release-notes.md, packages/core/src/common/validation/get-ajv-instance.spec.ts, packages/core/src/common/validation/get-ajv-instance.ts
=> Support custom OpenAPI "example" keyword in AJV validation

docs/docs/authentication/session-tokens.md, docs/docs/databases/typeorm/mongodb.md, docs/i18n/es/docusaurus-plugin-content-docs/current/authentication/session-tokens.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/authentication/session-tokens.md, docs/i18n/id/docusaurus-plugin-content-docs/current/authentication/session-tokens.md, packages/acceptance-tests/package-lock.json, packages/acceptance-tests/package.json, packages/acceptance-tests/src/additional/typeorm.mongodb-store.spec.ts, packages/acceptance-tests/src/additional/typeorm.redis-store.spec.ts, packages/acceptance-tests/src/docs/authentication/session-tokens/providing-a-custom-client-to-use-in-stores.feature.ts, packages/acceptance-tests/typings/mongodb/index.d.ts, packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/specs/app/src/app/entities/user.entity.mongodb.ts, packages/cli/src/generate/specs/entity/test-foo-bar.entity.mongodb.ts, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/cli/src/generate/templates/app/src/app/entities/user.entity.mongodb.ts, packages/cli/src/generate/templates/entity/entity.mongodb.ts, packages/examples/package-lock.json, packages/examples/package.json, packages/mongodb/package-lock.json, packages/mongodb/package.json, packages/typeorm/package-lock.json, packages/typeorm/package.json, packages/typeorm/typings/mongodb/index.d.ts
Database dependencies need to be upgraded
- No need to maintain to version of `mongodb` if using MongoDB store et TypeORM (use `mongodb@5`).
- Use `typeorm@0.3.17`
- The type `ObjectID` from `typeorm` is now called `ObjectId`.
- `mongodb@5.8`
- `typeorm@0.3.17`
- `pg@8.11`
=> Upgrade db dependencies for version 4

packages/cli/src/rmdir/rmdir.util.ts, packages/core/src/common/templates/render-error.ts, packages/core/src/common/templates/render.ts, packages/core/src/common/utils/is-in-file.util.ts, packages/graphiql/src/graphiql.controller.spec.ts, packages/graphiql/src/graphiql.controller.ts, packages/graphql/src/schema-from-type-paths.ts, packages/password/src/is-common.util.ts, packages/storage/src/local-disk.service.ts, packages/swagger/src/swagger-controller.spec.ts, packages/swagger/src/swagger-controller.ts
Some old code has been promisified in order to work with NodeJS API. In latest versions of Node, async functions are natively available with promises. Foal should use these functions directly instead.
=> Use fs native API with promises

docs/docs/tutorials/simple-todo-list/4-the-shell-script-create-todo.md, docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/simple-todo-list/4-the-shell-script-create-todo.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/simple-todo-list/4-the-shell-script-create-todo.md, docs/i18n/id/docusaurus-plugin-content-docs/current/tutorials/simple-todo-list/4-the-shell-script-create-todo.md, packages/cli/src/run-script/run-script.spec.ts, packages/cli/src/run-script/run-script.ts
When running a shell script with invalid arguments, Foal does not display all the errors.
For example, with this schema and this command call, we only get the following log message:
```typescript
export const schema = {
type: 'object', 
properties: {
email: { type: 'string', format: 'email', maxLength: 2 },
password: { type: 'string' },
n: { type: 'number', maximum: 10 }
},
required: ['password']
};
```
```bash
foal run my-script email=bar n=11
```
```
Error: The command line arguments must match format "email".
```
```
Script error: arguments must have required property 'password'.
Script error: the value of "email" must NOT have more than 2 characters.
Script error: the value of "email" must match format "email".
Script error: the value of "n" must be <= 10.
```
=> [CLI] Improve logging of script arguments validation errors

packages/core/src/common/logging/logger.utils.spec.ts, packages/core/src/common/logging/logger.utils.ts
As suggested [here](https://github.com/FoalTS/foal/issues/1247#issuecomment-1981685177)
=> Improve safety logging

docs/blog/version-4.5-release-notes.md, docs/docs/authentication/social-auth.md, docs/docs/tutorials/real-world-example-with-react/15-social-auth.md, packages/acceptance-tests/src/docs/authentication/social-auth/adding-social-auth-controllers.feature.ts, packages/acceptance-tests/src/docs/authentication/social-auth/using-social-auth-with-jwt.feature.ts, packages/acceptance-tests/src/docs/authentication/social-auth/using-social-auth-with-sessions.feature.ts, packages/examples/src/app/controllers/auth.controller.ts, packages/social/src/abstract-provider.service.spec.ts, packages/social/src/abstract-provider.service.ts, packages/social/src/google-provider.service.ts, packages/social/src/index.ts
- The type of the `userInfo` property returned by `GoogleProvider.getUserInfo` is of type `any`.
- In social auth, Foal only allows to get the consent page through a redirection and not a 200 response. This is not handy when building a SPA.
=> Improve `GoogleProvider` type and better support social auth for SPA

packages/cli/src/generate/specs/app/public/index.html, packages/cli/src/generate/templates/app/public/index.html
- The link in `index.html` to the official website pollutes the traffic analytics of the official website.
- The `index.html` content is not beautiful
*Before*
*After*
=> Improve welcome page and remove link to Foal website

docs/docs/tutorials/real-world-example-with-react/15-social-auth.md, package-lock.json, packages/cli/package.json, packages/cli/src/generate/generators/upgrade/upgrade.ts, packages/cli/typings/node-fetch/index.d.ts, packages/social/package.json, packages/social/src/abstract-provider.service.ts, packages/social/src/facebook-provider.service.ts, packages/social/src/github-provider.service.ts, packages/social/src/linkedin-provider.service.ts, packages/social/src/twitter-provider.service.ts, packages/social/typings/node-fetch/index.d.ts
Starting from Node 20 and 22, all tests pass by replacing `node-fetch` dependency with the native Node fetch API. Thus, the dependency can be removed.
See also #1267
- `@foal/cli`
- `node-fetch` removed
- `@foal/social`
- `node-fetch` removed
=> Remove `node-fetch` dependency

docs/blog/version-5.0-release-notes.md, docs/docs/architecture/controllers.md, docs/docs/architecture/hooks.md, packages/acceptance-tests/src/docs/architecture/hooks/forwarding-data-between-hooks.feature.ts, packages/core/src/core/http/context.ts, packages/socket.io/src/architecture/websocket-context.ts
When using `Context.state`, if we forget to provide a value for the generic type, the property works as if it was of type `any` which is not type-safe.
=> Make `Context.state` type to `{}` by default

.github/CONTRIBUTING.MD, docs/blog/version-5.0-release-notes.md, package-lock.json, package.json, packages/acceptance-tests/package.json, packages/aws-s3/package.json, packages/cli/package.json, packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/core/package.json, packages/examples/package.json, packages/graphiql/package.json, packages/graphql/package.json, packages/internal-test/package.json, packages/jwks-rsa/package.json, packages/jwt/package.json, packages/mongodb/package.json, packages/password/package.json, packages/redis/package.json, packages/social/package.json, packages/socket.io/package.json, packages/storage/package.json, packages/swagger/package.json, packages/typeorm/package.json, packages/typestack/package.json
We need to upgrade to the latest major version of TS which is v5.
=> Upgrade to TS v5

docs/blog/version-5.0-release-notes.md, docs/docs/common/graphql.md, packages/acceptance-tests/tsconfig.json, packages/aws-s3/tsconfig.json, packages/cli/src/generate/specs/app/tsconfig.json, packages/cli/src/generate/templates/app/tsconfig.json, packages/cli/tsconfig.json, packages/core/tsconfig.json, packages/examples/src/app/entities/user.entity.ts, packages/examples/tsconfig.json, packages/graphiql/tsconfig.json, packages/graphql/src/acceptance-test.spec.ts, packages/graphql/tsconfig.json, packages/internal-test/tsconfig.json, packages/jwks-rsa/tsconfig.json, packages/jwt/tsconfig.json, packages/mongodb/tsconfig.json, packages/password/tsconfig.json, packages/redis/tsconfig.json, packages/social/tsconfig.json, packages/socket.io/tsconfig.json, packages/storage/tsconfig.json, packages/swagger/tsconfig.json, packages/typeorm/tsconfig.json, packages/typestack/tsconfig.json, tsconfig.json
There is no need to compile to ES2021 anymore as Foal v5 supports Node 20 & 22. See: https://node.green
=> Compile to ES2023

docs/blog/version-5.0-release-notes.md, docs/docs/common/logging.md, packages/core/src/core/logging/logger.spec.ts, packages/core/src/core/logging/logger.ts, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts, packages/core/src/sessions/http/use-sessions.hook.spec.ts, packages/core/src/sessions/http/use-sessions.hook.ts, packages/jwt/src/http/jwt.hook.spec.ts, packages/jwt/src/http/jwt.hook.ts, packages/socket.io/src/socketio-controller.service.spec.ts, packages/socket.io/src/socketio-controller.service.ts
- The signature of the method `Logger.addLogContext` is different from the other logging methods (`info`, `warn`, etc) in the way to pass the context (key/value vs record).
- When we want to add merge a object to the log context, it is tedious to do it because we need to call the method for each key.
=> Make `addLogContext` accept a record with multiple params

docs/blog/version-5.0-release-notes.md, docs/docs/common/logging.md, packages/acceptance-tests/config/default.yml, packages/cli/src/generate/specs/app/config/default.json, packages/cli/src/generate/specs/app/config/default.mongodb.json, packages/cli/src/generate/specs/app/config/default.mongodb.yml, packages/cli/src/generate/specs/app/config/default.yml, packages/cli/src/generate/specs/app/config/e2e.json, packages/cli/src/generate/specs/app/config/e2e.mongodb.json, packages/cli/src/generate/specs/app/config/e2e.mongodb.yml, packages/cli/src/generate/specs/app/config/e2e.yml, packages/cli/src/generate/templates/app/config/default.json, packages/cli/src/generate/templates/app/config/default.mongodb.json, packages/cli/src/generate/templates/app/config/default.mongodb.yml, packages/cli/src/generate/templates/app/config/default.yml, packages/cli/src/generate/templates/app/config/e2e.json, packages/cli/src/generate/templates/app/config/e2e.mongodb.json, packages/cli/src/generate/templates/app/config/e2e.mongodb.yml, packages/cli/src/generate/templates/app/config/e2e.yml, packages/core/src/express/create-app.spec.ts, packages/core/src/express/create-app.ts, packages/examples/config/default.yml, packages/social/src/abstract-provider.service.spec.ts, packages/social/src/facebook-provider.service.spec.ts, packages/social/src/github-provider.service.spec.ts, packages/social/src/linkedin-provider.service.spec.ts, packages/social/src/twitter-provider.service.spec.ts, packages/storage/src/parse-and-validate-files.hook.spec.ts
- The use of `settings.loggerFormat` is deprecated. It should be removed in a major release.
- To support `loggerFormat: none` to disable HTTP logging, a new setting must be introduced with consistency with `settings.logger.logSocketioMessages`
=> Remove setting `loggerFormat` and add `logger.logHttpRequests`.

docs/blog/version-5.0-release-notes.md, packages/social/src/abstract-provider.service.spec.ts, packages/social/src/abstract-provider.service.ts
The `AbstractProvider.redirect` method is deprecated and should be removed in the next major version.
=> Remove deprecated `AbstractProvider.redirect` method

docs/blog/version-5.0-release-notes.md, docs/docs/authentication/session-tokens.md, docs/docs/databases/typeorm/introduction.md, package-lock.json, packages/acceptance-tests/package.json, packages/cli/src/generate/specs/app/package.json, packages/cli/src/generate/specs/app/package.mongodb.json, packages/cli/src/generate/specs/app/package.mongodb.yaml.json, packages/cli/src/generate/specs/app/package.yaml.json, packages/cli/src/generate/templates/app/package.json, packages/cli/src/generate/templates/app/package.mongodb.json, packages/examples/package.json, packages/typeorm/package.json
TypeORM needs to be upgraded to latest version in v5.
=> Upgrade TypeORM peer dependency to v0.3.20

docs/blog/version-5.0-release-notes.md, docs/docs/authentication/session-tokens.md, docs/docs/cli/shell-scripts.md, package-lock.json, packages/acceptance-tests/src/docs/authentication/session-tokens/revoking-sessions.feature.ts, packages/cli/package.json, packages/cli/src/generate/specs/script/test-foo-bar.ts, packages/cli/src/generate/templates/script/script.ts, packages/cli/src/run/run-script.spec.ts, packages/cli/src/run/run-script.ts, packages/examples/src/scripts/revoke-token.ts
When running a shell script, we often need to instantiate a `ServiceManager` to access services which is repetitive.
=> Provide a ServiceManager to shell scripts

docs/blog/version-5.0-release-notes.md, docs/docs/authentication/user-class.md, docs/docs/authorization/groups-and-permissions.md, docs/docs/cli/shell-scripts.md, docs/docs/common/async-tasks.md, docs/docs/tutorials/real-world-example-with-react/4-the-shell-scripts.md, docs/docs/tutorials/simple-todo-list/4-the-shell-script-create-todo.md, packages/acceptance-tests/src/additional/shell-scripts/create-group.spec.ts, packages/acceptance-tests/src/additional/shell-scripts/create-group.ts, packages/acceptance-tests/src/additional/shell-scripts/create-perm.spec.ts, packages/acceptance-tests/src/additional/shell-scripts/create-perm.ts, packages/cli/src/generate/specs/app/src/scripts/create-user.ts, packages/cli/src/generate/specs/script/test-foo-bar.ts, packages/cli/src/generate/templates/app/src/scripts/create-user.ts, packages/cli/src/generate/templates/script/script.ts, packages/cli/src/run/run-script.spec.ts, packages/cli/src/run/run-script.ts, packages/examples/src/scripts/create-user.ts
- It is not possible to use a log context in shell scripts or any services called from a shell script.
- When reading logs, it is not possible to aggregate logs through the execution of a given script as for an HTTP request.
- When a script succeeds or fails, no message is logged.
- Errors thrown in shell scripts are logged using `console.error` and not the logger which is not handy. When running a shell script in production, we may want to print the logs using a JSON format for example.
=> Improve logging in shell scripts

docs/blog/version-5.0-release-notes.md, docs/docs/architecture/controllers.md, docs/docs/tutorials/real-world-example-with-react/9-authenticated-api.md, packages/acceptance-tests/src/docs/architecture/controllers/reading-the-request-information.feature.ts, packages/core/src/core/http/context.ts, packages/core/src/core/routes/get-response.spec.ts, packages/core/src/core/routes/get-response.ts, packages/core/src/index.ts
In controllers, it is tedious to always have to type the `body`, `query` and `params` with some `as Foobar` statements.
=> Pass the request as second argument of controller methods

packages/cli/src/generate/specs/app/src/scripts/create-user.ts, packages/cli/src/generate/templates/app/src/scripts/create-user.ts
```
Error: src/scripts/create-user.ts(27,39): error TS2339: Property 'id' does not exist on type 'User'.
Error: Process completed with exit code 2.
```
It is actually named `_id` with MongoDB
=> Make create-user generated with createapp work with MongoDB

docs/docs/databases/other-orm/prisma.md, docs/docs/security/rate-limiting.md, packages/cli/src/generate/specs/app/src/index.ts, packages/cli/src/generate/templates/app/src/index.ts, packages/examples/src/index.ts
See #1316
When an error is raised in the `src/index.ts` file (outside Foal controllers, hooks or services), the error is not completely displayed. In particular, when the database connection fails (due to an incorrect port, for example), the error displayed is obscure.
This is due to the `catch` handler, which does not completely display the error but only the stack trace.
**Before**
**After**
=> Better display errors thrown in "main()"
