- README.md
- package.json
- packages/core/package.json
- packages/examples/README.md
- packages/express/README.md
- packages/sequelize/README.md
Foal slogan looked too much like ember.js one.
> Change slogan

- docs/README.md
To merge when https://github.com/FoalTS/generator-foal/pull/12 is merged.
> Update "get started"

- docs/basics/hooks.md
- docs/packages/common.md
- packages/common/package-lock.json
- packages/common/src/post-hooks/after-that-log.post-hook.spec.ts
- packages/common/src/post-hooks/after-that-log.post-hook.ts
- packages/common/src/post-hooks/after-that-remove-field.post-hook.spec.ts
- packages/common/src/post-hooks/after-that-remove-field.post-hook.ts
- packages/common/src/post-hooks/index.ts
- packages/common/src/pre-hooks/log.pre-hook.spec.ts
- packages/common/src/pre-hooks/log.pre-hook.ts
- packages/common/src/pre-hooks/method-not-allowed.pre-hook.spec.ts
- packages/common/src/pre-hooks/method-not-allowed.pre-hook.ts
- packages/common/src/pre-hooks/restrict-access-to-admin.pre-hook.spec.ts
- packages/common/src/pre-hooks/restrict-access-to-admin.pre-hook.ts
- packages/common/src/pre-hooks/restrict-access-to-authenticated.pre-hook.spec.ts
- packages/common/src/pre-hooks/restrict-access-to-authenticated.pre-hook.ts
> Add tests to @foal/common

- packages/common/gulpfile.js
- packages/core/gulpfile.js
- packages/ejs/gulpfile.js
- packages/examples/gulpfile.js
- packages/express/gulpfile.js
- packages/sequelize/gulpfile.js
The "MIT header" is only present in the `*.js` distributed files.
Add also the header to the files `*.d.ts`.
> In distributed files add MIT header to *.d.ts too.

- docs/basics/hooks.md
> Add more hook docs

- LICENSE
Update license date with `2018`.
> Update license date.

- README.md
- docs/SUMMARY.md
- docs/packages/ajv.md
- docs/packages/core.md
- packages/ajv/LICENSE
- packages/ajv/README.md
- packages/ajv/gulpfile.js
- packages/ajv/index.ts
- packages/ajv/package-lock.json
- packages/ajv/package.json
- packages/ajv/src/index.ts
- packages/ajv/src/validate.pre-hook.spec.ts
- packages/ajv/src/validate.pre-hook.ts
- packages/ajv/tsconfig-build.json
- packages/ajv/tsconfig.json
- packages/core/src/errors.ts
- packages/express/src/handle-errors.spec.ts
- packages/express/src/handle-errors.ts
FoalTS needs an input validator to check the data received by the server.
> Add input validation pre-hook.

- packages/core/src/foal.spec.ts
- packages/core/src/foal.ts
`Foal` should have unit tests.
> Add tests to foal.spec.ts

- docs/README.md
- docs/guide/1-introduction.md
- docs/guide/2-database-setup.md
- docs/guide/3-task-service.md
- docs/guide/4-rest-api-endpoint.md
- docs/guide/5-control-input-data.md
- docs/guide/6-add-a-logger.md
- docs/guide/7-test.md
> [Docs] Fix guide typos

- packages/sequelize/src/sequelize-connection.service.ts
See https://github.com/FoalTS/foal/issues/70.
Change sequelize connection config. More docs at https://github.com/sequelize/sequelize/issues/8417.
> Fix sequelize warning

- README.md
- docs/README.md
> Fix svg issue in markdown

- docs/README.md
- docs/guide/2-database-setup.md
https://github.com/FoalTS/generator-foal/pull/33
> Update docs with generator v0.4.0-alpha.6

- .github/CONTRIBUTING.MD
No contributing guidelines.
Add them.
> Add contributing.md

- lerna.json
- packages/ajv/package.json
- packages/authentication/package.json
- packages/authentication/src/authenticate.pre-hook.ts
- packages/authentication/src/authenticators/local-authenticator.service.ts
- packages/common/package.json
- packages/common/src/controller-factories/rest.controller-factory.ts
- packages/common/src/index.ts
- packages/common/src/object-does-not-exist.spec.ts
- packages/common/src/object-does-not-exist.ts
- packages/common/src/post-hooks/after-that-remove-field.post-hook.ts
- packages/core/package.json
- packages/core/src/classes/http-responses.spec.ts
- packages/core/src/classes/http-responses.ts
- packages/core/src/utils/combine-pre-hooks.ts
- packages/ejs/package.json
- packages/examples/package.json
- packages/express/package.json
- packages/express/src/utils/get-response.ts
- packages/express/src/utils/send-response.ts
- packages/sequelize/package.json
To fix `instanceof` issues across several npm packages:
> v0.4.0-beta.1

- lerna.json
- packages/ajv/package.json
- packages/cli/package.json
- packages/cli/src/build.ts
- packages/core/package.json
- packages/ejs/package.json
- packages/examples/package.json
> Prevent image loading when requiring html templates.

- lerna.json
- packages/cli/package.json
- packages/cli/src/build.ts
- packages/examples/package.json
> v0.5.0-alpha.4

- README.md
- packages/ajv/README.md
- packages/cli/README.md
- packages/core/README.md
- packages/ejs/README.md
- packages/examples/README.md
`https://foalts.gitbooks.io/docs/` -> `https://foalts.gitbook.io/docs/`
> Update docs URL.

- docs/README.md
Images cannot be centered in the new version of gitbook.
> [Docs] Remove logo.

- README.md
Gitbook didn't update on last merge.
> A commit to fix gitbook.

- docs/dev-tools/generators.md
- docs/security/authentication.md
- packages/cli/src/generate/generators/controller/create-controller.spec.ts
- packages/cli/src/generate/generators/controller/create-controller.ts
- packages/cli/src/generate/templates-spec/controller/test-foo-bar.controller.login.ts
- packages/cli/src/generate/templates/controller/controller.login.ts
- packages/cli/src/index.ts
https://github.com/FoalTS/foal/issues/154
> Generate `Login` controllers with the cli.

- docs/cookbook/rest-api.md
- docs/guide/4-rest-api-endpoint.md
- packages/cli/src/generate/templates-spec/service/test-foo-bar.service.entity-resource-collection.ts
- packages/cli/src/generate/templates/service/service.entity-resource-collection.ts
- packages/core/src/common/controllers/rest.controller.spec.ts
- packages/core/src/common/controllers/rest.controller.ts
- packages/core/src/common/errors/index.ts
- packages/core/src/common/errors/object-does-not-exist.ts
- packages/core/src/common/errors/permission-denied.spec.ts
- packages/core/src/common/errors/permission-denied.ts
- packages/core/src/common/errors/validation-error.ts
- packages/core/src/common/services/entity-resource-collection.service.spec.ts
- packages/core/src/common/services/entity-resource-collection.service.ts
- packages/core/src/common/services/resource-collection.interface.ts
> Change `IResourceCollection` interface.

- lerna.json
- packages/cli/package.json
- packages/cli/src/generate/templates-spec/app/package.1.json
- packages/cli/src/generate/templates/app/package.json
- packages/examples/package.json
> v0.6.0-beta.2

- docs/guide/2-handle-a-request.md
- docs/guide/4-rest-api-endpoint.md
- docs/guide/5-add-some-logging.md
- packages/cli/src/generate/generators/controller/create-controller.spec.ts
- packages/cli/src/generate/generators/controller/create-controller.ts
- packages/cli/src/generate/generators/entity/create-entity.spec.ts
- packages/cli/src/generate/generators/entity/create-entity.ts
- packages/cli/src/generate/generators/hook/create-hook.spec.ts
- packages/cli/src/generate/generators/hook/create-hook.ts
- packages/cli/src/generate/generators/module/create-module.spec.ts
- packages/cli/src/generate/generators/module/create-module.ts
- packages/cli/src/generate/generators/service/create-service.spec.ts
- packages/cli/src/generate/generators/service/create-service.ts
- packages/cli/src/generate/templates-spec/controller/index.1.ts
- packages/cli/src/generate/templates-spec/controller/test-foo-bar.controller.rest.ts
- packages/cli/src/generate/templates-spec/entity/index.1.ts
- packages/cli/src/generate/templates-spec/hook/index.1.ts
- packages/cli/src/generate/templates-spec/module/index.1.ts
- packages/cli/src/generate/templates-spec/module/index.parent.ts
- packages/cli/src/generate/templates-spec/service/index.1.ts
- packages/cli/src/generate/templates-spec/service/index.collection.ts
- packages/cli/src/generate/templates-spec/service/index.resolver.ts
- packages/cli/src/generate/templates-spec/service/test-foo-bar.service.entity-resource-collection.ts
- packages/cli/src/generate/templates/controller/controller.rest.ts
- packages/cli/src/generate/templates/module/index.ts
- packages/cli/src/generate/templates/service/service.entity-resource-collection.ts
> Add the exports to the `index.ts` when creating a file

- docs/deployment-and-environments/ship-to-production.md
- packages/cli/src/generate/specs/app/config/settings.production.json
- packages/cli/src/generate/templates/app/config/settings.production.json
- [https://www.owasp.org/index.php/Session_Management_Cheat_Sheet](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet)
- [https://www.owasp.org/index.php/Authentication_Cheat_Sheet](https://www.owasp.org/index.php/Authentication_Cheat_Sheet)
> Update session default configuration following OWASP recommandations

- docs/the-authentication-system/authentication.md
I was following the Docs steps and encountered these errors, hope this helps.
> [Docs] Updating authentication.md

- README.md
- packages/cli/README.md
- packages/core/README.md
- packages/ejs/README.md
There is no description on what the framework does.
Add one.
> Readme description

- docs/guide/1-introduction.md
Solve this: https://github.com/FoalTS/foal/issues/211.
Ask the user to rerun the command `npm run develop` in the "get started" guide.
> [Docs] Ask to rerun "npm run develop" in the guide.

- docs/SUMMARY.md
See:
- https://github.com/FoalTS/foal/pull/218
- https://github.com/FoalTS/foal/pull/222
> Update SUMMARY.md to have collapside menu in docs (second attempt).

- docs/SUMMARY.md
See:
- https://github.com/FoalTS/foal/pull/218
- https://github.com/FoalTS/foal/pull/222
- https://github.com/FoalTS/foal/pull/223
> Update SUMMARY.md to have collapside menu in docs (third attempt).

- docs/SUMMARY.md
- docs/tutorials/mongodb-todo-list/1-introduction.md
- docs/tutorials/mongodb-todo-list/2-with-typeorm.md
The documentation lacks an example on how to get started with FoalTS and MongoDB.
Add a "MongoDB To-Do List" tutorial.
> [Docs] Add tutorial "MongoDB To-Do List"

- packages/cli/package.json
- packages/cli/src/generate/utils/test-environment.ts
- packages/cli/src/test.ts
- Now using a file to change the NODE_ENV during tests
> Fix encoding problem in cli tests on Windows

- docs/SUMMARY.md
- docs/cookbook/build-a-public-api.md
See https://github.com/FoalTS/foal/issues/265.
> [Docs] Add documentation on how to build an Open API

- docs/SUMMARY.md
- docs/cookbook/404-page.md
- packages/core/e2e/404.spec.ts
- packages/core/src/core/routes/make-controller-routes.spec.ts
- packages/core/src/core/routes/make-controller-routes.ts
> Register the controller routes *after* its sub-controllers

- packages/cli/package-lock.json
- packages/cli/src/index.ts
Closes #310 
> Currently, the user can fire in n number of arguments with `foal createapp` which doesn't make any sense.
> The user is warned if he does so.
> Validate arguments for createapp command

- packages/core/package.json
- packages/core/src/express/create-app.spec.ts
- packages/core/src/express/create-app.ts
> Automatically parse cookies.

- packages/core/package.json
- packages/core/src/common/hooks/validate-headers.hook.spec.ts
- packages/core/src/core/http/contexts.ts
> Add a type to Context.request

- docs/development-environment/code-generation.md
- packages/cli/src/generate/generators/script/create-script.spec.ts
- packages/cli/src/generate/generators/script/create-script.ts
> [@foal/cli] Make `foal g script` generate scripts from anywhere in the project.

- lerna.json
- packages/core/package.json
- packages/core/src/core/config.spec.ts
- packages/core/src/core/config.ts
- packages/examples/package.json
- packages/jwt/package.json
- packages/mongoose/package.json
- packages/typeorm/package.json
[Config] v0.8.0 didn't look at the configuration files in the right order.
> Fix config order issue (v0.8.1)

- docs/tutorials/mongodb-todo-list/5-the-rest-api.md
findOneAndDelete was deleting the first todo in the database, no matter which id.
changed it to findByIdAndRemove
> fix of issue #361

- lerna.json
- packages/cli/package.json
- packages/cli/src/generate/specs/app/config/default.json
- packages/cli/src/generate/specs/app/config/default.yml
- packages/cli/src/generate/templates/app/config/default.json
- packages/cli/src/generate/templates/app/config/default.yml
- packages/core/package.json
- packages/examples/package.json
- packages/jwt/package.json
- packages/mongoose/package.json
- packages/typeorm/e2e/auth-redirect.spec.ts
- packages/typeorm/package.json
> v0.8.2 (actually v0.8.5)

- packages/cli/package.json
- packages/cli/src/create-secret/create-secret.spec.ts
- packages/cli/src/create-secret/create-secret.ts
- packages/cli/src/create-secret/index.ts
- packages/cli/src/index.ts
> [@foal/cli] Add "foal createsecret" command

- docs/authentication-and-access-control/jwt.md
> Improve the documentation on JWT

- docs/SUMMARY.md
- docs/cloud/firebase.md
Explain how to deploy an application with Firebase (requested by a user).
> [Docs] Add Cloud / Firebase

- docs/SUMMARY.md
- docs/frontend-integration/jsx-server-side-rendering.md
See #381 
Add a small tutorial on how to do JSX Server-Side Rendering with React.
> [Docs] Add docs on JSX SSR with React

- benchmarks/benchmark.txt
- benchmarks/express.js
- benchmarks/foal.js
- benchmarks/foal.ts
- benchmarks/package-lock.json
- benchmarks/package.json
- benchmarks/run.sh
- benchmarks/tsconfig.json
> Add benchmark to compare performance between Express & Foal (example with JWT auth)

- docs/frontend-integration/angular-react-vue.md
Just some missing text from the docs
Added the text!
> Update command examples for frontend integration

- docs/authentication-and-access-control/jwt.md
Add documentation on how to refresh JSON Web tokens.
> [Docs] How to refresh JWTs

- docs/SUMMARY.md
- docs/serializing-and-deserializing.md
- docs/validation-and-sanitization.md
See #460 
Add docs on how to use [class-validator](https://www.npmjs.com/package/class-validator), [class-transformer](https://www.npmjs.com/package/class-transformer).
> [TypeStack] Serialization & validation.

- docs/cookbook/expressjs.md
- docs/cookbook/generate-tokens.md
- docs/cookbook/limit-repeated-requests.md
- docs/frontend-integration/single-page-applications.md
- packages/acceptance-tests/package-lock.json
- packages/acceptance-tests/package.json
- packages/acceptance-tests/src/examples/architecture/hooks.spec.ts
- packages/acceptance-tests/src/examples/cookbook/404-page.spec.ts
- packages/acceptance-tests/src/examples/cookbook/expressjs.spec.ts
- packages/acceptance-tests/src/examples/cookbook/generate-tokens.spec.ts
- packages/acceptance-tests/src/examples/cookbook/limit-repeated-requests.spec.ts
- packages/acceptance-tests/src/examples/frontend-integration/public/index.html
- packages/acceptance-tests/src/examples/frontend-integration/single-page-applications.spec.ts
Check that code examples in the documentation compile and work as expected. Add more acceptance tests for this.
Improve and test:
> [Docs] Improve the docs and test the examples with acceptance tests (I)

- packages/core/src/express/500.debug.html
See https://github.com/FoalTS/foal/issues/479
- [-] Add/update/check docs (code comments and docs/ folder).
- [-] Add/update/check tests.
- [-] Update/check the cli generators.
> Prettify error page in dev

- docs/api-section/public-api-and-cors-requests.md
> [Docs] CORS requests with cookies

- docs/SUMMARY.md
- docs/cookbook/root-imports.md
> [Docs] Add root imports.

- package-lock.json
- packages/swagger/package-lock.json
- packages/swagger/src/index.no-primary.spec.html
- packages/swagger/src/index.no-primary.ui-options.spec.html
- packages/swagger/src/index.primary.spec.html
- packages/swagger/src/index.tpl.html
- packages/swagger/src/index.url.spec.html
- packages/swagger/src/index.url.ui-options.spec.html
- packages/swagger/src/swagger-controller.spec.ts
- packages/swagger/src/swagger-controller.ts
Resolve #486
> Ok, I see. I took a look at the [Swagger documentation](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) as well, most of the options can be "stringified".
> 
> Here how I see how to update to the `SwaggerController`:
> 
> ```ts
> export abstract class SwaggerController {
>   // ...
> 
>   abstract options: ... // Current options that are used both to render the templates and determine the route behaviors.
> 
>   uiOptions: object = {} // Additional swagger UI options that can be override.
> 
>   // ...
> }
> 
> // Example
> class DocumentationController extends SwaggerController {
>   options = { controller: ApiController };
> 
>   uiOptions = { docExpansion: 'none' };
> }
> ```
> 
> To implement this, we need to:
> 
> * Update `index.tpl.html`.
> …
> Add swagger ui config

- docs/tutorials/simple-todo-list/5-the-rest-api.md
There was a small typo at line 90. 
Corrected it from objet to object
> typo at line 90. Its written as objet which should be object

- docs/tutorials/simple-todo-list/6-validation-and-sanitization.md
Found typo on document
Remove it
> fix typo on /6-validation-and-sanitization.md

- docs/architecture/hooks.md
- packages/acceptance-tests/src/examples/architecture/hooks.spec.ts
> [Docs] Test a hook post function

- packages/cli/src/generate/specs/app/src/index.mongodb.ts
- packages/cli/src/generate/specs/app/src/index.ts
- packages/cli/src/generate/templates/app/src/index.mongodb.ts
- packages/cli/src/generate/templates/app/src/index.ts
Resolves #534.
Update CLI templates
> [CLI] Prevent infinite loop on main error

- docs/comparison-with-other-frameworks.md
> Add more comparisons to other frameworks

- docs/validation-and-sanitization.md
- packages/core/src/common/utils/get-ajv-instance.spec.ts
- packages/core/src/common/utils/get-ajv-instance.ts
Resolves #532.
Support AJV "nullable" option in Foal's config.
> Support AJV "nullable" option.

- docs/authentication-and-access-control/session-tokens.md
- docs/security/csrf-protection.md
- packages/acceptance-tests/package.json
- packages/acceptance-tests/src/mongoose-db.mongodb-store.spec.ts
- packages/acceptance-tests/src/mongoose-db.redis-store.spec.ts
- packages/core/src/sessions/session-store.ts
- packages/core/src/sessions/token.hook.spec.ts
- packages/core/src/sessions/token.hook.ts
- packages/mongodb/LICENSE
- packages/mongodb/README.md
- packages/mongodb/package.json
- packages/mongodb/src/index.ts
- packages/mongodb/src/mongodb-store.service.spec.ts
- packages/mongodb/src/mongodb-store.service.ts
- packages/mongodb/tsconfig-build.json
- packages/mongodb/tsconfig.json
- packages/redis/src/redis-store.service.spec.ts
- packages/swagger/src/swagger-controller.ts
- packages/typeorm/src/typeorm-store.service.spec.ts
- unit_test.sh
> [Sessions][Auth] Support MongoDB as session storage

- docs/serializing-and-deserializing.md
- docs/validation-and-sanitization.md
- packages/acceptance-tests/package.json
- packages/acceptance-tests/src/examples/validation-and-sanitization.spec.ts
- packages/acceptance-tests/src/typestack.spec.ts
- packages/typestack/LICENSE
- packages/typestack/README.md
- packages/typestack/package.json
- packages/typestack/src/index.ts
- packages/typestack/src/unserialize-body.hook.spec.ts
- packages/typestack/src/unserialize-body.hook.ts
- packages/typestack/src/validate-body.hook.spec.ts
- packages/typestack/src/validate-body.hook.ts
- packages/typestack/tsconfig-build.json
- packages/typestack/tsconfig.json
- unit_test.sh
> Add TypeStack unserialization and validation hooks

- docs/authentication-and-access-control/password-management.md
> [Docs] Add documentation on password salts.

- docs/testing/e2e-testing.md
- docs/testing/unit-testing.md
> [Docs] Better explain how to use unit test cmds

- docs/api-section/graphql.md
- packages/graphql/package.json
- packages/graphql/src/acceptance-test.spec.ts
> [Docs] Add TypeGraphQL example

- docs/cloud/aws-beanstalk.md
- [*] Add/update/check docs (code comments and docs/ folder).
> Correct Max by Mac

- docs/tutorials/mongodb-todo-list/6-validation-and-sanitization.md
- docs/tutorials/mongodb-todo-list/7-unit-testing.md
- docs/tutorials/simple-todo-list/6-validation-and-sanitization.md
- docs/tutorials/simple-todo-list/7-unit-testing.md
- samples/tutorials/01-simple-todo-list/src/app/controllers/api.controller.ts
- samples/tutorials/02-multi-user-todo-list-mpa/src/app/controllers/api.controller.ts
- samples/tutorials/03-mongodb-todo-list/src/app/controllers/api.controller.ts
The tutorials use `@ValidateParams` which is cumbersome
Use `@ValidatePathParam` instead.
> Improve tutorials by using ValidatePathParam

- docs/api-section/openapi-and-swagger-ui.md
Just fixed the code in an example about `@ApiResponse`
> fix an example in the docs

- docs/databases/typeorm.md
> [Docs] Add configuration examples with MySQL and Postgres

- docs/authentication-and-access-control/groups-and-permissions.md
I was following the docs and couldn't get project to run after adding UserWithPermissions. Turns out I was missing the export.
See my issue created in haste: https://github.com/FoalTS/foal/issues/616
> Docs: groups-and-permissions.md add to example

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/graphql/package-lock.json
- packages/graphql/package.json
- packages/mongodb/package-lock.json
- packages/mongodb/package.json
- packages/swagger/package-lock.json
- packages/swagger/package.json
- @foal/cli
- ajv@6.11
- @foal/core
- ajv@6.11
- @foal/graphql
- ajv@6.11
- @foal/mongodb
- mongodb@3.5
- @foal/swagger
- swagger-ui-dist@3.25
> [v1.6.0] Upgrade external dependencies

- .github/FUNDING.yml
This PR adds the possibility to support the framework by making a recurring donation.
https://github.com/sponsors/LoicPoullain
> [Sponsoring] Add LoicPoullain to Github Sponsors

- docs/cookbook/error-handling.md
- docs/utilities/logging-and-debugging.md
- packages/core/src/express/handle-errors.spec.ts
- packages/core/src/express/handle-errors.ts
> [Config] Add an option not to log errors

- docs/databases/typeorm.md
> Fix TypeORM link

- packages/aws-s3/package-lock.json
- packages/aws-s3/package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/index.ts
- packages/jwks-rsa/package-lock.json
- packages/jwks-rsa/package.json
- @foal/cli
- commander@5.0
- @foal/aws-s3
- aws-sdk@2.640
- @foal/jwks-rsa
- jwks-rsa@1.7
> [v1.7.0] Upgrade dependencies

- docs/architecture/services-and-dependency-injection.md
> Fix typo in services-and-dependency-injection.md

- docs/databases/typeorm.md
- docs/file-system/local-and-cloud-storage.md
The introduction.md file has renamed to quick-start in https://github.com/FoalTS/foal/commit/0c97ea070b81a93732352628f9aeb5b0dd5f8d75#diff-940ed56792a2dcfa3cb97a9ac25bf8a8
> Fix a broken link

- docs/tutorials/simple-todo-list/3-the-todo-model.md
Minor wording, spelling and punctuation fixes in tutorial docs.
N/A
N/A
> Docs: wording, spelling and punctuation fixes

- docs/tutorials/simple-todo-list/2-introduction.md
Minor clarification and grammatical fixes in second page of introduction.
N/A
- [N/A ] Add/update/check tests.
- [N/A] Update/check the cli generators.
> Minor grammatical fixes in 2-introduction.md

- .github/CONTRIBUTING.MD
> [CONTRIBUTING] Add dependency, testing & version policies and improve on-boarding

- packages/cli/src/generate/generators/angular/connect-angular.ts
- packages/cli/src/generate/generators/vue/connect-vue.ts
- packages/cli/src/index.ts
> Make all frontend `connect` projects build on unix

- benchmarks/run.sh
- e2e_test.sh
- unit_test.sh
A small improvement for shell scripts :+1: 
```
-e  Exit immediately if a command exits with a non-zero status.
```
> Any command failure ends shell script execution

- docs/api-section/rest-blueprints.md
- packages/cli/src/generate/generators/rest-api/create-rest-api.spec.ts
- packages/cli/src/generate/generators/rest-api/create-rest-api.ts
- packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.auth.ts
- packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.current-dir.auth.ts
- packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.spec.auth.ts
- packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.spec.current-dir.auth.ts
- packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.spec.ts
- packages/cli/src/generate/specs/rest-api/test-foo-bar.entity.auth.ts
- packages/cli/src/generate/templates/rest-api/controller.auth.ts
- packages/cli/src/generate/templates/rest-api/controller.current-dir.auth.ts
- packages/cli/src/generate/templates/rest-api/controller.spec.auth.ts
- packages/cli/src/generate/templates/rest-api/controller.spec.current-dir.auth.ts
- packages/cli/src/generate/templates/rest-api/controller.spec.current-dir.ts
- packages/cli/src/generate/templates/rest-api/entity.auth.ts
- packages/cli/src/index.ts
Fixes #366 
`foal g rest-api product --auth` adds an `owner: User` in the generated entity and uses it in the controller.
> [CLI] Support --auth on "foal g rest-api"

- packages/core/src/core/http/contexts.ts
Custom Type for ctx.state
Add third optional custom generic type argument to context definition.
> Support custom type for ctx.state

- docs/tutorials/multi-user-todo-list/3-the-shell-scripts.md
Fixes #720
Create a new project by following the tutorial. Run `npm run lint` and notice errors. See #720 for details.
> Fix linter errors in tutorial shell scripts

- packages/acceptance-tests/src/upload-and-download.spec.ts
- packages/acceptance-tests/src/upload-and-download.typeorm.spec.ts
- packages/core/src/core/http/http-responses.spec.ts
- packages/core/src/core/http/http-responses.ts
- packages/storage/src/abstract-disk.service.spec.ts
- packages/storage/src/abstract-disk.service.ts
> fix http-responses typo mistakes

- docs/cookbook/expressjs.md
> explainn better when postMiddlewares are executed

- packages/cli/src/generate/specs/app/package.json
- packages/cli/src/generate/specs/app/package.mongodb.json
- packages/cli/src/generate/specs/app/package.mongodb.yaml.json
- packages/cli/src/generate/specs/app/package.yaml.json
- packages/cli/src/generate/templates/app/package.json
- packages/cli/src/generate/templates/app/package.mongodb.json
- packages/cli/src/generate/templates/app/package.mongodb.yaml.json
- packages/cli/src/generate/templates/app/package.yaml.json
> Fix some npm and yarn warnings on install

- packages/cli/src/run-script/run-script.spec.ts
- packages/cli/src/run-script/run-script.ts
> [CLI] Catch rejected promises in shell scripts

- docs/security/csrf-protection.md
Corrected `setCsrfCookie` imports
Incorrect `setCsrfCookie` import statement on Docs
Corrected `setCsrfCookie` import statements
Not sure if following things are relevant.
> setCsrfCookie import correction

- docs/authentication-and-access-control/groups-and-permissions.md
> [Groups & Perms] Make cmd work on all OS

- docs/authentication-and-access-control/quick-start.md
- docs/authentication-and-access-control/social-auth.md
- docs/security/csrf-protection.md
- docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
- docs/tutorials/multi-user-todo-list/7-the-signup-page.md
- packages/acceptance-tests/src/authentication/session-token.cookie.redirection.spec.ts
- packages/acceptance-tests/src/authentication/session-token.cookie.spec.ts
- packages/acceptance-tests/src/csrf/regular-web-app.stateful.spec.ts
- packages/acceptance-tests/src/csrf/spa-and-api.stateful.spec.ts
- packages/core/src/sessions/create-session.spec.ts
- packages/core/src/sessions/read-session.spec.ts
- packages/core/src/sessions/session.spec.ts
- packages/core/src/sessions/session.ts
- packages/core/src/sessions/token.hook.spec.ts
- packages/core/src/sessions/token.hook.ts
- packages/typeorm/src/typeorm-store.service.spec.ts
- packages/typeorm/src/typeorm-store.service.ts
> [V2][Sessions] Remove the need of setSessionCookie in login

- docs/upgrade-to-v2/file-upload-and-download.md
- packages/core/src/sessions/use-sessions.hook.spec.ts
- packages/core/src/sessions/use-sessions.hook.ts
> [V2] Do not save sessions on 500

- .github/CONTRIBUTING.MD
> fix little typo lerna url

- docs/frontend-integration/angular-react-vue.md
Fixes https://github.com/FoalTS/foal/issues/562#issuecomment-734947757
> [Docs] Precise docs in frontend integration

- docs/docs/common/validation-and-sanitization.md
- packages/acceptance-tests/package-lock.json
- packages/acceptance-tests/package.json
- packages/acceptance-tests/src/docs/common/validation-and-sanitization/referencing-and-reusing-validation-schemas.feature.ts
- packages/acceptance-tests/src/docs/common/validation-and-sanitization/returning-custom-validation-error-messages.feature.ts
- packages/acceptance-tests/typings/ajv-errors/index.d.ts
> Add docs on validation custom errors and schema references

- docs/docusaurus.config.js
- docs/src/theme/BlogSidebar/index.js
- docs/src/theme/BlogSidebar/styles.module.css
- docs/src/theme/TOC/index.js
- docs/src/theme/TOC/styles.module.css
This PR adds [EthicalAds](https://www.ethicalads.io/) to the docs.
> [Docs] Add ethicalads components

- docs/docusaurus.config.js
- docs/src/pages/newsletter.jsx
> [Website] Add newsletter subscription widget

- docs/docusaurus.config.js
Resolves #858 
The survey is closed. This PR removes the link to the survey on the website.
> [Docs] Remove survey link

- docs/docs/api-section/gRPC.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/api-section/gRPC.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/api-section/gRPC.md
- docs/sidebars.js
- packages/acceptance-tests/package-lock.json
- packages/acceptance-tests/package.json
- packages/acceptance-tests/src/docs/api-section/spec.proto
- packages/acceptance-tests/src/docs/api-section/using-grpc-framework.feature.ts
This PR adds documentation on how to use gRPC framework in Foal
> [Docs] Add gRPC example

- docs/docs/api-section/openapi-and-swagger-ui.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
components/schema/ -> components/schemas/
typo
> fix typos in docs/openapi-and-swagger

- docs/docs/authentication-and-access-control/session-tokens.md
- docs/docs/databases/using-another-orm.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/authentication-and-access-control/session-tokens.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/databases/using-another-orm.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/authentication-and-access-control/session-tokens.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/databases/using-another-orm.md
- packages/acceptance-tests/src/docs/databases/using-another-orm/creating-a-custom-fetch-user-function.feature.ts
- packages/cli/src/generate/specs/app/gitignore
- packages/cli/src/generate/templates/app/gitignore
- packages/core/src/index.ts
- packages/core/src/sessions/fetch-user.interface.ts
- packages/core/src/sessions/index.ts
- packages/core/src/sessions/use-sessions.hook.spec.ts
- packages/core/src/sessions/use-sessions.hook.ts
- packages/jwt/src/jwt-optional.hook.ts
- packages/jwt/src/jwt-required.hook.ts
- packages/jwt/src/jwt.hook.spec.ts
- packages/jwt/src/jwt.hook.ts
- packages/typeorm/src/utils/fetch-mongodb-user.util.spec.ts
- packages/typeorm/src/utils/fetch-mongodb-user.util.ts
- packages/typeorm/src/utils/fetch-user-with-permissions.util.spec.ts
- packages/typeorm/src/utils/fetch-user-with-permissions.util.ts
- packages/typeorm/src/utils/fetch-user.util.spec.ts
- packages/typeorm/src/utils/fetch-user.util.ts
> Add Prisma docs & allow to access services in fetchUser function

- docs/blog/version-2.3-release-notes.md
- packages/social/src/abstract-provider.service.spec.ts
- packages/social/src/abstract-provider.service.ts
> [V2] [Social] Fix state bad URL characters

- docs/docs/architecture/configuration.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/architecture/configuration.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/architecture/configuration.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/architecture/configuration.md
This PR adds a note in the documentation about the use of [dotenv](https://www.npmjs.com/package/dotenv).
> [Docs] Add note on the dotenv library

- docs/docs/architecture/services-and-dependency-injection.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/architecture/services-and-dependency-injection.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/architecture/services-and-dependency-injection.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/architecture/services-and-dependency-injection.md
Documentation mini bug: incorrect import in code example of architecture md :).
> Fix typo in architecture docs code example

- docs/docs/upgrade-to-v2/openapi.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/upgrade-to-v2/openapi.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/upgrade-to-v2/openapi.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/upgrade-to-v2/openapi.md
> fix typo in upgrade to v2 openapi docs

- docs/docs/tutorials/real-world-example-with-react/1-introduction.md
- docs/docs/tutorials/real-world-example-with-react/3-the-models.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/1-introduction.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/2-database-set-up.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/3-the-models.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/1-introduction.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/10-auth-with-react.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/11-sign-up.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/12-file-upload.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/13-csrf.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/14-production-build.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/15-social-auth.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/2-database-set-up.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/3-the-models.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/4-the-shell-scripts.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/5-our-first-route.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/6-swagger-interface.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/7-add-frontend.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/8-authentication.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/9-authenticated-api.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/1-introduction.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/2-database-set-up.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/3-the-models.md
> [Docs] Translate React tutorial to French

- docs/docs/tutorials/real-world-example-with-react/1-introduction.md
- docs/docs/tutorials/real-world-example-with-react/10-auth-with-react.md
- docs/docs/tutorials/real-world-example-with-react/9-authenticated-api.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/1-introduction.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/10-auth-with-react.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/11-sign-up.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/12-file-upload.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/13-csrf.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/14-production-build.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/15-social-auth.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/2-database-set-up.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/3-the-models.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/4-the-shell-scripts.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/5-our-first-route.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/6-swagger-interface.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/7-add-frontend.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/8-authentication.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/9-authenticated-api.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/10-auth-with-react.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/9-authenticated-api.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/1-introduction.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/10-auth-with-react.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/tutorials/real-world-example-with-react/9-authenticated-api.md
> [Docs] Translate React tutorial to Spanish

- docs/package-lock.json
- docs/package.json
- docs/src/css/custom.scss
- docs/src/theme/BlogPostItem/index.js
- docs/src/theme/BlogPostItem/styles.module.css
- docs/src/theme/TOC/index.js
- docs/src/theme/TOC/styles.module.css
This PR updates the website to docusaurus beta.1 to remove a CSS hack.
It also update the swizzled components.
Related issue: #958
> [Website] Update to docusaurus beta.1

- packages/cli/src/generate/fixtures/angular/angular.empty.json
- packages/cli/src/generate/generators/angular/connect-angular.spec.ts
- packages/cli/src/generate/generators/angular/connect-angular.ts
- packages/cli/src/generate/specs/angular/angular.empty.json
> [CLI] Support empty angular.json for connect cmd

- docs/docs/authentication-and-access-control/session-tokens.md
- docs/docs/websockets.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/authentication-and-access-control/session-tokens.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/websockets.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/authentication-and-access-control/session-tokens.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/websockets.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/authentication-and-access-control/session-tokens.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/websockets.md
- packages/acceptance-tests/package-lock.json
- packages/acceptance-tests/package.json
- packages/acceptance-tests/src/additional/typeorm.redis-store.spec.ts
- packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/providing-a-custom-client-to-use-in-stores.feature.ts
- packages/acceptance-tests/src/docs/websocket/using-redis-to-manage-multiple-node-servers.feature.ts
- packages/redis/package-lock.json
- packages/redis/package.json
- packages/redis/src/redis-store.service.spec.ts
- packages/redis/src/redis-store.service.ts
- packages/redis/tsconfig.json
- packages/redis/typings/redis/index.d.ts
- packages/socket.io/package-lock.json
- packages/socket.io/package.json
- packages/socket.io/src/socketio-controller.service.spec.ts
- packages/socket.io/tsconfig.json
- packages/socket.io/typings/redis/index.d.ts
Upgrade all major versions to v3.
Previous PR: #1028.
> Upgrade redis dependencies to redis@4

- .github/workflows/documentation.yml
- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- docs/src/css/custom.scss
- docs/src/theme/BlogPostItem/index.js
- docs/src/theme/TOC/index.js
- docs/src/theme/TOC/styles.module.css
- Need to be up-to-date with latest beta version of Docusaurus
- The colors of the navbar are incorrect on mobile screens.
> [Website] Upgrade docusaurus to v2.0.0-beta.15 and fix bad nav colors on Mobile

- docs/blog/version-2.8-release-notes.md
- docs/docs/file-system/local-and-cloud-storage.md
- packages/aws-s3/src/s3-disk.service.spec.ts
- packages/aws-s3/src/s3-disk.service.ts
> [AWS S3] Support server-side encryption for file uploads

- docs/docs/websockets.md
- packages/socket.io/src/socketio-controller.service.spec.ts
- packages/socket.io/src/socketio-controller.service.ts
> [WS] Allow to emit events without payload or cb

- packages/core/src/core/routes/make-controller-routes.spec.ts
- packages/core/src/core/routes/make-controller-routes.ts
> Show security requirements, servers and external doc of sub-controllers in Swagger auto-generated document

- docs/docs/deployment-and-environments/checklist.md
> [Docs] Add note on failing builds on remote host

- packages/cli/src/generate/specs/app/src/app/entities/user.entity.mongodb.ts
- packages/cli/src/generate/specs/entity/test-foo-bar.entity.mongodb.ts
- packages/cli/src/generate/specs/rest-api/controllers/test-foo-bar.controller.auth.subdir.ts
- packages/cli/src/generate/specs/rest-api/controllers/test-foo-bar.controller.auth.ts
- packages/cli/src/generate/specs/rest-api/controllers/test-foo-bar.controller.spec.auth.subdir.ts
- packages/cli/src/generate/specs/rest-api/controllers/test-foo-bar.controller.spec.auth.ts
- packages/cli/src/generate/specs/rest-api/controllers/test-foo-bar.controller.spec.subdir.ts
- packages/cli/src/generate/specs/rest-api/controllers/test-foo-bar.controller.spec.ts
- packages/cli/src/generate/specs/rest-api/controllers/test-foo-bar.controller.subdir.ts
- packages/cli/src/generate/specs/rest-api/controllers/test-foo-bar.controller.ts
- packages/cli/src/generate/templates/app/src/app/entities/user.entity.mongodb.ts
- packages/cli/src/generate/templates/entity/entity.mongodb.ts
- packages/cli/src/generate/templates/rest-api/controllers/controller.auth.ts
- packages/cli/src/generate/templates/rest-api/controllers/controller.spec.auth.ts
- packages/cli/src/generate/templates/rest-api/controllers/controller.spec.ts
- packages/cli/src/generate/templates/rest-api/controllers/controller.ts
> [CLI] Always use Active Record pattern by default (`BaseEntity`)

- docs/docs/authentication-and-access-control/groups-and-permissions.md
- docs/docs/authentication-and-access-control/user-class.md
- packages/acceptance-tests/src/additional/authorization/groups-and-permissions.spec.ts
- packages/acceptance-tests/src/additional/controller-inheritance.spec.ts
- packages/acceptance-tests/src/additional/shell-scripts/create-group.spec.ts
- packages/acceptance-tests/src/additional/shell-scripts/create-group.ts
- packages/acceptance-tests/src/additional/shell-scripts/create-perm.spec.ts
- packages/acceptance-tests/src/additional/shell-scripts/create-perm.ts
- packages/examples/src/app/controllers/profile.controller.ts
- packages/examples/src/scripts/create-user.ts
> Remove use of deprecated `getManager` and `getRepository` functions

- docs/docs/authentication-and-access-control/session-tokens.md
- packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/providing-a-custom-client-to-use-in-stores.feature.ts
- packages/typeorm/src/typeorm-store.service.spec.ts
- packages/typeorm/src/typeorm-store.service.ts
- packages/typeorm/src/utils/fetch-user-with-permissions.util.ts
TODO
- `TypeORMStore.setConnection` and `TypeORMStore.close` do not exist anymore.
> Make `TypeORMStore` use `DataSource`

- packages/cli/src/generate/specs/app/package.json
- packages/cli/src/generate/specs/app/package.mongodb.json
- packages/cli/src/generate/specs/app/package.mongodb.yaml.json
- packages/cli/src/generate/specs/app/package.yaml.json
- packages/cli/src/generate/templates/app/package.json
- packages/cli/src/generate/templates/app/package.mongodb.json
- packages/cli/src/generate/templates/app/package.mongodb.yaml.json
- packages/cli/src/generate/templates/app/package.yaml.json
> Fix concurrently issue on some OS

- packages/storage/src/local-disk.service.ts
- packages/storage/src/validate-multipart-form-data-body.hook.spec.ts
- packages/storage/src/validate-multipart-form-data-body.hook.ts
> Do not throw on uploads with empty filenames

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- docs/src/css/custom.scss
- docs/src/pages/index.jsx
- docs/src/pages/index.module.scss
- docs/tailwind.config.js
When visiting the landing page, visitors should know that Foal is used by real companies so as to be confident to test and then use the framework.
> [Website] Prepare landing page structure to add company logs

- docs/docs/tutorials/real-world-example-with-react/12-file-upload.md
- Fixed 2 minor typos in the file uplaod example
- Added filename to docs as small hint for new users
Minor doc issues that prevent copy and paste working
> docs(typos) Fix minor typos in file upload example

- packages/cli/src/generate/specs/app/package.json
- packages/cli/src/generate/specs/app/package.mongodb.json
- packages/cli/src/generate/specs/app/package.mongodb.yaml.json
- packages/cli/src/generate/specs/app/package.yaml.json
- packages/cli/src/generate/templates/app/package.json
- packages/cli/src/generate/templates/app/package.mongodb.json
- packages/cli/src/generate/templates/app/package.mongodb.yaml.json
- packages/cli/src/generate/templates/app/package.yaml.json
The CLI was still installing version 2 of `@foal/cli`
> Make `createapp` install v3 of `@foal/cli`

- docs/docs/common/validation-and-sanitization.md
Out of date reference in the docs
> docs(minor) Change reference to Ajv version (6 -> 8)

- docs/blog/version-3.1-release-notes.md
- docs/docs/cli/commands.md
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/generate/fixtures/upgrade/package.json
- packages/cli/src/generate/generators/app/create-app.ts
- packages/cli/src/generate/generators/index.ts
- packages/cli/src/generate/generators/upgrade/index.ts
- packages/cli/src/generate/generators/upgrade/upgrade.spec.ts
- packages/cli/src/generate/generators/upgrade/upgrade.ts
- packages/cli/src/generate/utils/index.ts
- packages/cli/src/generate/utils/install-dependencies.ts
- packages/cli/src/generate/utils/logger.ts
- packages/cli/src/index.ts
- packages/cli/typings/node-fetch/index.d.ts
> [CLI] Add `foal upgrade [version]` command

- packages/acceptance-tests/package-lock.json
- packages/acceptance-tests/package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/graphql/package-lock.json
- packages/graphql/package.json
- `@foal/cli`
- `ajv@8.12`
- `@foal/core`
- `ajv@8.12`
- `@foal/graphql`
- `ajv@8.12`
> Upgrade dependencies for v3.3.0

- docker-compose.yml
- docs/docs/databases/typeorm/introduction.md
- docs/i18n/es/docusaurus-plugin-content-docs/current/databases/typeorm/introduction.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/databases/typeorm/introduction.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/databases/typeorm/introduction.md
- packages/typeorm/package.json
- packages/typeorm/src/entities/group.entity.spec.ts
- packages/typeorm/src/entities/permission.entity.spec.ts
- packages/typeorm/src/entities/user-with-permissions.entity.spec.ts
- packages/typeorm/src/typeorm-store.service.spec.ts
- packages/typeorm/src/typeorm-store.service.ts
> Drop MariaDB support

- packages/core/src/express/create-app.ts
> add-xml-header-request

- packages/cli/src/generate/fixtures/angular/angular.empty.json
- packages/cli/src/generate/fixtures/angular/angular.json
- packages/cli/src/generate/generators/angular/connect-angular.ts
- packages/cli/src/generate/specs/angular/angular.empty.json
- packages/cli/src/generate/specs/angular/angular.json
> [CLI] Fix "foal connect angular" to support latest versions of Angular

- docs/blog/version-4.2-release-notes.md
- docs/docs/common/file-storage/upload-and-download-files.md
- packages/core/src/express/create-app.spec.ts
- packages/core/src/express/create-app.ts
> Allow to pass `cacheControl` option to static middleware

- docs/docs/architecture/configuration.md
- docs/docs/databases/typeorm/introduction.md
- docs/versioned_docs/version-1.x/authentication-and-access-control/jwt.md
- docs/versioned_docs/version-1.x/authentication-and-access-control/password-management.md
- docs/versioned_docs/version-1.x/databases/typeorm.md
- docs/versioned_docs/version-1.x/deployment-and-environments/configuration.md
- docs/versioned_docs/version-1.x/file-system/local-and-cloud-storage.md
- docs/versioned_docs/version-1.x/file-system/upload-and-download-files.md
- docs/versioned_docs/version-1.x/utilities/templating.md
- docs/versioned_docs/version-2.x/architecture/configuration.md
- docs/versioned_docs/version-3.x/architecture/configuration.md
- docs/versioned_docs/version-3.x/databases/typeorm/introduction.md
- docs/versioned_sidebars/version-1.x-sidebars.json
See https://docusaurus.io/docs/migration/v3
> [Docs] Prepare to upgrade to Docusaurus v3

- packages/core/src/common/logging/logger.utils.spec.ts
- packages/core/src/common/logging/logger.utils.ts
- packages/core/src/express/create-app.spec.ts
- packages/core/src/express/create-app.ts
> Fix logger error when there is no status code

- docs/blog/version-5.0-release-notes.md
- docs/docs/authentication/social-auth.md
- packages/social/src/abstract-provider.service.spec.ts
- packages/social/src/abstract-provider.service.ts
- packages/social/src/google-provider.service.ts
The return type of the method `getUserInfoFromTokens` is any whereas we have its type.
> Improve `AbstractProvider.getUserInfoFromTokens` return type

- docs/blog/2021-02-03-version-2.1-release-notes.md
- docs/blog/2021-02-17-whats-new-in-version-2-part-1.md
- docs/blog/2021-02-25-version-2.2-release-notes.md
- docs/blog/2021-03-02-whats-new-in-version-2-part-2.md
- docs/blog/2021-03-11-whats-new-in-version-2-part-3.md
- docs/blog/2021-04-08-whats-new-in-version-2-part-4.md
- docs/blog/2021-04-22-version-2.3-release-notes.md
- docs/blog/2021-05-19-version-2.4-release-notes.md
- docs/blog/2021-06-11-version-2.5-release-notes.md
- docs/blog/2021-09-19-version-2.6-release-notes.md
- docs/blog/2021-12-12-version-2.7-release-notes.md
- docs/blog/2022-02-13-version-2.8-release-notes.md
- docs/blog/2022-05-29-version-2.9-release-notes.md
- docs/blog/2022-06-13-FoalTS-2022-survey-is-open.md
- docs/blog/2022-08-11-version-2.10-release-notes.md
- docs/blog/2022-10-09-version-2.11-release-notes.md
- docs/blog/2022-11-01-version-3.0-release-notes.md
- docs/blog/2022-11-28-version-3.1-release-notes.md
- docs/blog/2023-04-04-version-3.2-release-notes.md
- docs/blog/2023-08-13-version-3.3-release-notes.md
- docs/blog/2023-09-11-version-4.0-release-notes.md
- docs/blog/2023-10-24-version-4.1-release-notes.md
- docs/blog/2023-10-29-version-4.2-release-notes.md
- docs/blog/2024-04-16-version-4.3-release-notes.md
- docs/blog/2024-04-25-version-4.4-release-notes.md
- docs/blog/2024-08-22-version-4.5-release-notes.md
- docs/blog/authors.yml
- docs/package-lock.json
- docs/package.json
- docs/src/pages/newsletter.jsx
> Upgrade docusaurus to v3.5
